// ─── PORTFOLIO & CREDIT AGREEMENT DATA ──────────────────────────────
// Extracted from CreditRiskMonitor.jsx for code-splitting optimization.
// This module is lazy-loaded by Vite as a separate chunk.

// ─── PORTFOLIO DATA: LCID & RIVN ────────────────────────────────────────────
export const PORTFOLIO = [
{
id: "LCID",
pm: "YP",
name: "Lucid Group Inc.",
sector: "EV / Automotive",
exposure: 25000000,
sp: "NR",
moodys: "NR",
fitch: "NR",
impliedRating: "CCC+",
outlook: "Negative",
watchlist: true,
cds5y: 1850,
cds5yChg: 95,
bondSpread: 980,
bondSpreadChg: 45,
eqPrice: 10.06,
eqChg: -3.5,
mktCap: 3.26,
ltDebt: 2740,
totalDebt: 2740,
cash: 4600,
ebitda: -2890,
intExp: 145,
revenue: 1354,
netIncome: -3682,
totalAssets: 8400,
totalEquity: 3000,
fcf: -2650,
currentAssets: 3300,
currentLiab: 2600,
grossLeverage: -0.95,
netLeverage: -0.63,
intCov: -19.9,
debtToEquity: 0.91,
currentRatio: 1.27,
roic: -52.4,
deliveries2025: 15841,
deliveriesGuidance2026: "25,000 - 27,000",
productionGuidance2026: "25,000 - 27,000",
cashBurnQtr: -814,
liquidityRunway: "~5-6 qtrs at current burn",
// Adjusted Cash Burn Components (FY2025, $M)
// Source: Q4 FY2025 Earnings Release, 10-K, Earnings Presentation
adjBurn: {
adjEBITDA: -2130,         // Company-reported Non-GAAP Adj. EBITDA FY2025
adjEBITDA_src: "Q4 2025 Earnings Release — GAAP-to-Non-GAAP reconciliation",
incomeTaxes: 5,            // Recurring income taxes (minimal — pre-profit, NOL carryforwards)
incomeTaxes_src: "10-K FY2025; near-zero cash taxes due to NOLs",
prefDividends: 0,          // No cash preferred dividends (PIF converts accrue, non-cash)
prefDividends_src: "No cash preferred dividends; PIF redeemable converts are non-cash accretion",
maintCapex: null,          // Maintenance capex not separately disclosed
totalCapex: 868,           // Total CapEx FY2025
totalCapex_src: "Stocktitan / 10-K: $868.2M; 2026 guidance: $1.2B-$1.4B",
currentLTD: 0,             // Current portion of LT debt (2026 converts retired in Nov 2025)
currentLTD_src: "2026 converts retired via $975M 2031 note proceeds; no near-term maturities",
intExpCash: 95,            // Cash interest expense FY2025
intExpCash_src: "10-K FY2025; converts + SIDF + GIB draws",
},
liquidityBreakdown: {
totalLiquidity: 4600,
components: [
{ category: "Cash & Cash Equivalents", amount: 998, type: "cash", sub: [
{ label: "Bank Deposits & Money Market Funds", amount: 612 },
{ label: "U.S. Treasury Bills (< 3 mo.)", amount: 268 },
{ label: "Restricted Cash", amount: 118 },
]},
{ category: "Short-Term Investments (< 1 yr)", amount: 820, type: "st_invest", sub: [
{ label: "U.S. Treasury Securities", amount: 385 },
{ label: "U.S. Agency Securities", amount: 195 },
{ label: "Corporate Debt Securities (IG)", amount: 155 },
{ label: "Related Party Investments (PIF)", amount: 85 },
]},
{ category: "Long-Term Investments (> 1 yr)", amount: 282, type: "lt_invest", sub: [
{ label: "U.S. Treasury Securities", amount: 142 },
{ label: "Corporate Bonds (IG-rated)", amount: 90 },
{ label: "Related Party Investments (PIF)", amount: 50 },
]},
{ category: "Undrawn Credit Facilities", amount: 2415, type: "facility", sub: [] },
],
// Source: Lucid Q4 FY2025 Earnings Presentation, Slide 9 — "Liquidity Supports Execution and Growth"
// Total Liquidity $4.6B = Cash/Inv $2.1B + DDTL $2.0B + ABL $397M + GIB $38M
facilities: [
{ name: "PIF Delayed Draw Term Loan (DDTL)", committed: 1980, drawn: 0, available: 1980, maturity: "Aug 2029", rate: "Negotiated", secured: "Unsecured", notes: "Increased from $750M to ~$2.0B (Nov 2025); 5-yr term from Aug 2024; fully undrawn; PIF (majority shareholder) is counterparty" },
{ name: "ABL Revolving Credit Facility", committed: 1000, drawn: 0, available: 397, maturity: "Jun 2027", rate: "SOFR + spread", secured: "Senior Secured", notes: "BofA-led syndicate (10 banks); availability = lesser of (committed amount, borrowing base); borrowing base driven by eligible inventory + receivables minus reserves; $350M LC sublimit, $100M swingline sublimit; springing maturity 91 days prior to any >$500M debt maturity; Q4 2025 availability: $397M per earnings presentation" },
{ name: "GIB Revolving Credit Facility", committed: 507, drawn: 469, available: 38, maturity: "Feb 2028", rate: "SAIBOR + 1.40%", secured: "Unsecured", notes: "SAR 1.9B (~$507M) with Gulf International Bank S.A. (PIF-related party); renewed Feb 2025; 0.25%/yr commitment fee on unused; loans up to 12-mo tenor; general corporate purposes; Q4 2025 availability: $38M per earnings presentation — majority drawn for KSA operations" },
{ name: "SIDF Term Loan", committed: 1400, drawn: 735, available: 665, maturity: "2029-2032 (amortizing)", rate: "Subsidized (KSA)", secured: "Senior Secured", notes: "Saudi Industrial Development Fund; for AMP-2 factory construction in KSA; partially drawn; disbursements tied to project milestones; SAR-denominated; not included in reported $4.6B total liquidity figure" },
],
debtMaturities: [
{ year: "2026", amount: 0, desc: "2026 converts retired via 2031 note proceeds" },
{ year: "2027", amount: 0, desc: "No maturities; SIDF amortization ongoing" },
{ year: "2028", amount: 469, desc: "GIB Revolving Facility ($469M drawn; matures Feb 2028)" },
{ year: "2029", amount: 0, desc: "DDTL maturity window (5-yr from Aug 2024)" },
{ year: "2030", amount: 1100, desc: "5.00% Convertible Senior Notes (Apr 2030)" },
{ year: "2031", amount: 975, desc: "1.75% Convertible Senior Notes (Nov 2031)" },
{ year: "Other", amount: 665, desc: "SIDF draws + other KSA obligations" },
],
},
earningsDate: "2026-05-04",
earningsTime: "After Close",
lastEarnings: "Miss — EPS -$3.62 vs -$2.89 est.",
earningsCallSummary: {
date: "February 24, 2026",
quarter: "Q4 FY2025",
source: "SEC Filing: Exhibit 99.1 (Q4 FY2025 Earnings Release) + Earnings Call Transcript",
keyFinancials: [
"Q4 revenue of $522.7M, up 123% YoY; FY2025 revenue $1,353.8M, up 68% YoY",
"GAAP diluted net loss per share of $(3.62) in Q4; $(12.09) for FY2025",
"Total liquidity of ~$4.6B at quarter-end (cash/investments $2.1B + undrawn facilities $2.5B)",
],
production: [
"Q4 production of 7,874 vehicles (up 133% YoY); FY2025 production 17,840 vehicles (nearly doubled YoY)",
"538 vehicles reclassified — did not complete final validation at AMP-2 Saudi Arabia facility; shifted to 2026",
"Q4 deliveries of 5,345 (up 72% YoY) — eighth consecutive quarter of record deliveries",
"2026 production guidance: 25,000–27,000 vehicles (40-50% increase)",
],
creditRelevant: [
"CEO Winterhoff cited 'extraordinary macro turbulences' — tariffs, incentive roll-offs, shifting EV demand, supply chain disruptions",
"Focus on improving gross margin through lower material costs, fixed cost absorption via scale, and operational efficiencies",
"Cost actions intended to extend liquidity runway into first half of 2027",
"Layoffs of 12% of U.S. workforce announced post-earnings to improve cost structure",
"Robotaxi partnership with Uber/Nuro announced; Lucid Lunar concept revealed at March Investor Day",
],
strategicItems: [
"Gravity SUV ramp continues — primary 2026 revenue growth driver",
"Midsize vehicle platform in development; first production expected in 2026-2027 timeframe",
"PIF remains majority shareholder and primary liquidity backstop via undrawn $1.98B DDTL",
"Path to profitability details deferred to March 12 Investor Day",
],
analystQA: [
"Clearest path to positive gross margin? — CFO: Better material costs, scale absorption, efficiencies; more detail at Investor Day",
"Tesla competitive threat? — CEO: Lucid is natural successor to Model S/X; seeing uptick in Tesla owner inquiries",
],
},
analystRating: "Hold",
targetPrice: 12.86,
news: [
{ date: "2026-03-19", src: "CNBC", headline: "Lucid receives first Buy rating in months as Citi initiates coverage", sentiment: "positive" },
{ date: "2026-03-17", src: "Reuters", headline: "Uber expands robotaxi deal with Nvidia; Lucid partnership in focus", sentiment: "positive" },
{ date: "2026-03-12", src: "Bloomberg", headline: "Lucid reveals Lunar robotaxi concept and Uber partnership at Investor Day", sentiment: "positive" },
{ date: "2026-03-09", src: "CNBC", headline: "Lucid lays off 12% of U.S. workforce to cut costs and improve gross margin", sentiment: "negative" },
{ date: "2026-02-25", src: "CNBC", headline: "Lucid widely misses earnings expectations, forecasts slowing EV growth in 2026", sentiment: "negative" },
{ date: "2026-02-24", src: "Bloomberg", headline: "Lucid files prospectus to register 69M shares for resale by PIF and Uber affiliates", sentiment: "negative" },
],
ratingHistory: [
{ date: "2025-11", sp: "NR", moodys: "NR", fitch: "NR", event: "$975M convertible notes issued (2031 maturity)" },
{ date: "2025-06", sp: "NR", moodys: "NR", fitch: "NR", event: "Gravity SUV production begins" },
{ date: "2024-06", sp: "NR", moodys: "NR", fitch: "NR", event: "1.25% convertible notes issued (2026 maturity)" },
],
financials: [
{ period: "FY2025", rev: 1354, ebitda: -2890, ni: -3682, debt: 2740, cash: 4600 },
{ period: "FY2024", rev: 875, ebitda: -3050, ni: -3420, debt: 2000, cash: 4500 },
{ period: "FY2023", rev: 595, ebitda: -3290, ni: -2828, debt: 2050, cash: 4850 },
{ period: "FY2022", rev: 608, ebitda: -3050, ni: -1304, debt: 2000, cash: 6260 },
],
research: [
{ date: "2026-03-18", firm: "Citi", action: "Initiate Buy", pt: 16, summary: "Gravity SUV ramp + robotaxi partnership with Uber creates optionality; PIF backing provides liquidity floor." },
{ date: "2026-03-12", firm: "RBC Capital", action: "Hold", pt: 11, summary: "Investor Day laid out path to FCF positive but execution remains high-risk; 2026 deliveries of 25-27K still uncertain." },
{ date: "2026-02-25", firm: "Wolfe Research", action: "Underperform", pt: 6, summary: "Q4 miss underscores cash burn challenge; $975M convert offering extends runway but dilution concerns persist." },
{ date: "2026-02-15", firm: "Morgan Stanley", action: "Hold", pt: 10, summary: "Gravity driving demand visibility but negative gross margins remain a structural concern." },
],
},
{
id: "RIVN",
pm: "YP",
name: "Rivian Automotive Inc.",
sector: "EV / Automotive",
exposure: 35000000,
sp: "NR",
moodys: "NR",
fitch: "NR",
impliedRating: "B-",
outlook: "Developing",
watchlist: true,
cds5y: 1280,
cds5yChg: -65,
bondSpread: 720,
bondSpreadChg: -30,
eqPrice: 15.02,
eqChg: -6.8,
mktCap: 19.3,
ltDebt: 4967,
totalDebt: 4400,
cash: 6082,
ebitda: -2063,
intExp: 320,
revenue: 5387,
netIncome: -3626,
totalAssets: 14900,
totalEquity: 4600,
fcf: -2489,
currentAssets: 8600,
currentLiab: 3700,
grossLeverage: -1.60,
netLeverage: 0.97,
intCov: -8.6,
debtToEquity: 0.97,
currentRatio: 2.32,
roic: -18.6,
deliveries2025: 42284,
deliveriesGuidance2026: "62,000 - 67,000 (incl. R2)",
productionGuidance2026: "48,000 - 52,000",
cashBurnQtr: -530,
liquidityRunway: "~8-10 qtrs (incl. DOE loan)",
// Adjusted Cash Burn Components (FY2025, $M)
adjBurn: {
adjEBITDA: -2063,         // Sum of quarterly Adj. EBITDA: Q1 -$329M + Q2 -$667M + Q3 -$602M + Q4 -$465M
adjEBITDA_src: "Q4 FY2025 Press Release (Exhibit 99.1); sum of quarterly Non-GAAP Adj. EBITDA",
incomeTaxes: 8,            // Recurring income taxes (minimal — pre-profit)
incomeTaxes_src: "10-K FY2025; nominal cash taxes; substantial NOL carryforwards",
prefDividends: 0,          // No preferred dividends
prefDividends_src: "No preferred stock outstanding",
maintCapex: null,          // Not disclosed separately
totalCapex: 1710,          // Sum of quarterly CapEx: Q1 $338M + Q2 $462M + Q3 $447M + Q4 $463M
totalCapex_src: "Q4 FY2025 Press Release; heavy growth CapEx for R2 tooling + Georgia plant",
currentLTD: 0,             // 2026 floating rate notes retired via green note proceeds
currentLTD_src: "2026 notes retired Jun 2025; next maturity 2028 converts",
intExpCash: 285,           // Cash interest expense FY2025
intExpCash_src: "10-K FY2025; green notes + convertible notes",
},
liquidityBreakdown: {
totalLiquidity: 6590,
components: [
{ category: "Cash & Cash Equivalents", amount: 3574, type: "cash", sub: [
{ label: "Bank Deposits & Money Market Funds", amount: 2100 },
{ label: "U.S. Treasury Bills (< 3 mo.)", amount: 1430 },
{ label: "Restricted Cash", amount: 44 },
]},
{ category: "Short-Term Investments", amount: 2508, type: "st_invest", sub: [
{ label: "U.S. Treasury Securities", amount: 1200 },
{ label: "U.S. Agency Securities", amount: 520 },
{ label: "Corporate Debt Securities (IG)", amount: 420 },
{ label: "Asset-Backed Securities (AAA)", amount: 230 },
{ label: "Commercial Paper", amount: 138 },
]},
{ category: "Undrawn Credit Facilities", amount: 508, type: "facility", sub: [] },
],
facilities: [
{ name: "ABL Revolving Credit Facility", committed: 1500, drawn: 0, available: 508, maturity: "Apr 2028", rate: "SOFR + spread", secured: "First Lien (ABL Priority Collateral)", notes: "Upsized to $1.5B in Apr 2023 (from $750M); undrawn; availability of $508M after borrowing base and outstanding LCs; LC sub-limit $1.0B; minimum liquidity covenant of $1.0B (falls away upon FCCR > 1.0x for 2 consecutive quarters); in compliance with all covenants as of Dec 31, 2025" },
{ name: "DOE ATVM Loan (Conditional)", committed: 6600, drawn: 0, available: 0, maturity: "TBD", rate: "Subsidized (DOE)", secured: "Secured by New Horizon assets", notes: "Up to $6.6B conditionally approved for Georgia plant (R2 production); NOT a confirmed liquidity source — final terms, closing conditions, and disbursement schedule still pending; availability begins only after final loan closing and project milestone draws" },
],
debtMaturities: [
{ year: "2026", amount: 0, desc: "Retired via green note proceeds" },
{ year: "2027", amount: 0, desc: "No maturities" },
{ year: "2028", amount: 1500, desc: "Convertible Notes (4.625%)" },
{ year: "2029", amount: 0, desc: "No maturities" },
{ year: "2030", amount: 1500, desc: "Convertible Notes (3.625%)" },
{ year: "2031", amount: 1250, desc: "Green Secured Notes (issued Jun 2025)" },
{ year: "Other", amount: 150, desc: "Other obligations & leases" },
],
},
earningsDate: "2026-05-12",
earningsTime: "After Close",
lastEarnings: "Beat — EPS -$0.53 vs -$0.71 est.",
earningsCallSummary: {
date: "February 12, 2026",
quarter: "Q4 FY2025",
source: "SEC Filing: Exhibit 99.1 (Q4 FY2025 Earnings Release) + Earnings Call Transcript",
keyFinancials: [
"Q4 consolidated revenue of $1,286M; automotive revenue $839M (down 45% YoY due to loss of $270M regulatory credits + expired tax incentives)",
"Software & services revenue surged to $447M in Q4 (up 109% YoY), driven by Volkswagen JV",
"Q4 consolidated gross profit of $120M; FY2025 gross profit $144M — first full year of positive gross profit (>$1.3B improvement vs FY2024)",
"Q4 adjusted EBITDA loss of -$465M; FY2025 adjusted EBITDA guided at -$1.8B to -$2.1B",
"Liquidity of ~$6.1B at year-end (cash, equivalents, and short-term investments)",
],
production: [
"Q4 production of 10,974 vehicles; Q4 deliveries of 9,745 vehicles",
"FY2025 deliveries of 42,247 vehicles (down 18% YoY due to tax credit expiration impact)",
"2026 delivery guidance: 62,000–67,000 vehicles",
"R2 pre-production builds receiving outstanding reviews; customer deliveries expected Q2 2026",
],
creditRelevant: [
"First full year of positive consolidated gross profit — a major credit inflection point",
"Automotive gross profit still negative at -$59M in Q4 and -$432M for FY2025; software/services ($576M GP) offsets losses",
"2026 capex guidance: $1.95B–$2.05B (Georgia plant + R2 launch)",
"Adjusted EBITDA positive no longer expected in 2027 — pushed further out",
"Cash burn remains elevated; FY2025 cash position declined from $7.7B to $6.1B (-$1.6B); total liquidity $6.6B including $508M ABL availability",
],
strategicItems: [
"R2 SUV launch at $45,000–$57,990 pricing opens mass-market addressable opportunity",
"Volkswagen JV progressing — vehicles delivered for winter testing 13 months after formation; ~60% of Q4 software revenue",
"Unveiled RAP1 in-house autonomy processor at December AI Day; Universal Hands-Free expanded to 3.5M+ miles of roads",
"Uber $1.25B equity-linked investment for 10,000 autonomous R2 robotaxis (milestone-based, announced March 2026)",
"DOE ATVM $6.6B conditional loan — disbursement still pending final closing",
],
analystQA: [
"R2 demand signals? — CEO Scaringe: Pre-production reviews very strong; fills gap for quality EVs under $50K",
"Path to auto gross profit positive? — CFO: Targeting automotive gross profit positive by end of 2026 through R2 economics + continued R1 cost reductions",
"VW JV revenue sustainability? — Management: Expect continued growth; VW product launches using Rivian architecture in 2027",
],
},
analystRating: "Buy",
targetPrice: 17.74,
news: [
{ date: "2026-03-20", src: "Bloomberg", headline: "Rivian shares fall 6.8% as Middle East tensions weigh on cyclical stocks", sentiment: "negative" },
{ date: "2026-03-19", src: "Reuters", headline: "Uber invests $1.25B in Rivian for 10,000 autonomous R2 robotaxis", sentiment: "positive" },
{ date: "2026-03-19", src: "CNBC", headline: "Rivian no longer expects to be adjusted EBITDA positive in 2027", sentiment: "negative" },
{ date: "2026-03-12", src: "CNBC", headline: "Rivian launches R2 SUV at $57,990; deliveries begin spring 2026", sentiment: "positive" },
{ date: "2026-03-10", src: "Bloomberg", headline: "TD Cowen upgrades Rivian to Buy on R2 demand potential", sentiment: "positive" },
{ date: "2026-02-13", src: "Reuters", headline: "Deutsche Bank and UBS both upgrade Rivian on improving fundamentals", sentiment: "positive" },
],
ratingHistory: [
{ date: "2025-06", sp: "NR", moodys: "NR", fitch: "NR", event: "$1.25B green notes issued (2031), redeemed 2026 floating-rate notes" },
{ date: "2024-10", sp: "NR", moodys: "NR", fitch: "NR", event: "DOE ATVM loan of up to $6.6B conditionally approved" },
{ date: "2024-06", sp: "NR", moodys: "NR", fitch: "NR", event: "VW invests $5B; joint venture announced" },
],
financials: [
{ period: "FY2025", rev: 5387, ebitda: -2063, ni: -3626, debt: 4400, cash: 6082 },
{ period: "FY2024", rev: 4970, ebitda: -3200, ni: -4746, debt: 5400, cash: 7700 },
{ period: "FY2023", rev: 4434, ebitda: -4760, ni: -5432, debt: 4430, cash: 9410 },
{ period: "FY2022", rev: 1658, ebitda: -6340, ni: -6752, debt: 1500, cash: 11570 },
],
research: [
{ date: "2026-03-19", firm: "Evercore ISI", action: "Outperform", pt: 22, summary: "Uber robotaxi deal validates R2 platform; $1.25B investment de-risks 2027-28 production ramp." },
{ date: "2026-03-12", firm: "TD Cowen", action: "Upgrade to Buy", pt: 20, summary: "R2 reveal stronger than expected; $45K-$58K pricing opens mass-market addressable opportunity." },
{ date: "2026-03-10", firm: "Goldman Sachs", action: "Buy", pt: 19, summary: "Physical AI and autonomous driving optionality underappreciated; R2 + Georgia plant are catalysts." },
{ date: "2026-02-17", firm: "DA Davidson", action: "Downgrade to UW", pt: 11, summary: "Cash burn unsustainable without R2 success; EBITDA positive pushed beyond 2027." },
{ date: "2026-02-13", firm: "Deutsche Bank", action: "Upgrade to Buy", pt: 18, summary: "R1 cost reductions improving; R2 platform economics fundamentally better than R1." },
],
},
// ─── NEW PORTFOLIO ADDITIONS ─────────────────────────────────────────────
{
id: "CENT",
pm: "YP",
name: "Central Garden & Pet Co.",
sector: "Consumer Products",
exposure: 15000000,
sp: "BB",
moodys: "B1",
fitch: "BB",
impliedRating: "BB-",
outlook: "Stable",
watchlist: false,
cds5y: 320,
cds5yChg: -10,
bondSpread: 285,
bondSpreadChg: -8,
eqPrice: 34.48,
eqChg: 1.8,
mktCap: 2.1,
ltDebt: 1200,
totalDebt: 1200,
cash: 721,
ebitda: 430,
intExp: 62,
revenue: 3350,
netIncome: 165,
totalAssets: 4800,
totalEquity: 1600,
fcf: 280,
currentAssets: 1450,
currentLiab: 780,
grossLeverage: 2.8,
netLeverage: 1.1,
intCov: 6.9,
debtToEquity: 0.75,
currentRatio: 1.86,
roic: 8.2,
cashBurnQtr: 70,
liquidityRunway: "Adequate — investment grade profile",
adjBurn: {
adjEBITDA: 430,
adjEBITDA_src: "FY2025 10-K; non-GAAP adj EBITDA",
incomeTaxes: 55,
incomeTaxes_src: "FY2025 10-K; ~25% effective rate",
prefDividends: 0,
prefDividends_src: "No preferred stock outstanding",
maintCapex: 30,
totalCapex: 55,
totalCapex_src: "FY2026 guidance $50-60M; FY2025 actual ~$55M",
currentLTD: 0,
currentLTD_src: "No near-term debt maturities until 2028",
intExpCash: 62,
intExpCash_src: "FY2025 10-K; senior notes interest",
},
liquidityBreakdown: {
totalLiquidity: 1471,
components: [
{ category: "Cash & Cash Equivalents", amount: 721, type: "cash", sub: [
{ label: "Unrestricted Cash", amount: 680 },
{ label: "Restricted Cash", amount: 41 },
]},
{ category: "Undrawn Credit Facilities", amount: 750, type: "facility", sub: [] },
],
facilities: [
{ name: "ABL Revolving Credit Facility", committed: 750, drawn: 0, available: 750, maturity: "2028", rate: "SOFR + spread", secured: "Senior Secured", notes: "No borrowings outstanding at FY2025 year-end; availability based on borrowing base of eligible inventory & receivables" },
],
debtMaturities: [
{ year: "2026", amount: 0, desc: "No maturities" },
{ year: "2027", amount: 0, desc: "No maturities" },
{ year: "2028", amount: 600, desc: "6.125% Senior Notes due 2028" },
{ year: "2029", amount: 0, desc: "No maturities" },
{ year: "2030", amount: 600, desc: "4.125% Senior Notes due 2030" },
{ year: "Other", amount: 0, desc: "" },
],
},
earningsDate: "2026-05-06",
earningsTime: "After Close",
lastEarnings: "Beat — EPS $0.21 vs $0.14 est.",
earningsCallSummary: {
date: "February 4, 2026",
quarter: "Q1 FY2026 (Dec 2025)",
source: "SEC Filing: Exhibit 99.1 (Q1 FY2026 Earnings Release)",
keyFinancials: [
"Q1 net sales $617M, down 6% YoY — driven by shipment timing shift into Q2 and portfolio optimization",
"Gross margin expanded 110 bps to 30.9%; non-GAAP gross margin 30.8%",
"GAAP diluted EPS $0.11; non-GAAP EPS $0.21 (flat YoY, beat consensus of $0.14)",
"Net interest expense $8M, consistent with prior year",
],
production: [
"Revenue decline attributed to retailer spring inventory shipment timing, not demand destruction",
"Continued portfolio optimization — rationalizing lower-margin pet durables and select live plants",
"Closed UK operations; transitioning European business to direct model",
"Completed Champion USA tuck-in acquisition post-quarter (livestock feed-through fly control)",
],
creditRelevant: [
"Total debt $1.2B unchanged; gross leverage 2.9x (within 3.0-3.5x target range)",
"No ABL borrowings outstanding at quarter-end — $750M revolver fully available",
"Cash position of $721M — record level",
"Reaffirmed FY2026 non-GAAP diluted EPS guidance of $2.70 or better",
"CapEx guidance $50-60M for fiscal 2026",
],
strategicItems: [
"Cost & Simplicity program embedded in operations — closed 16 legacy facilities to date",
"Central to Home strategy focused on pet and garden consumables and innovation",
"Increased M&A activity anticipated, particularly in consumable businesses",
"Investing in digital capabilities and e-commerce to adapt to shifting consumer behaviors",
],
analystQA: [
"Path to growth? — CEO Lahanas: Embedding innovation in culture alongside cost discipline; results will build over time",
"Consumer headwinds? — Management: Consumer still value-focused; portfolio optimization improving margin mix despite top-line pressure",
],
},
analystRating: "Hold",
targetPrice: 42.00,
news: [
{ date: "2026-02-04", src: "Business Wire", headline: "Central Garden & Pet Q1 FY2026 earnings beat on margins despite 6% revenue decline", sentiment: "positive" },
{ date: "2026-01-15", src: "Reuters", headline: "Central Garden completes Champion USA tuck-in acquisition for livestock segment", sentiment: "positive" },
{ date: "2025-11-24", src: "Zacks", headline: "Central Garden delivers record FY2025 bottom-line results and cash position", sentiment: "positive" },
],
ratingHistory: [
{ date: "2025-06", sp: "BB", moodys: "B1", fitch: "BB", event: "Stable outlook reaffirmed; Cost & Simplicity driving margin improvement" },
{ date: "2024-01", sp: "BB", moodys: "B1", fitch: "BB", event: "Moody's affirms B1 CFR with stable outlook" },
],
financials: [
{ period: "FY2025", rev: 3350, ebitda: 430, ni: 165, debt: 1200, cash: 721 },
{ period: "FY2024", rev: 3280, ebitda: 385, ni: 118, debt: 1200, cash: 580 },
{ period: "FY2023", rev: 3170, ebitda: 340, ni: 89, debt: 1250, cash: 510 },
{ period: "FY2022", rev: 3640, ebitda: 410, ni: 156, debt: 1300, cash: 450 },
],
research: [
{ date: "2026-02-05", firm: "Zacks", action: "Hold", pt: 40, summary: "Q1 beat on margins but revenue miss on shipment timing; portfolio optimization ongoing." },
{ date: "2025-11-25", firm: "KeyBanc", action: "Overweight", pt: 45, summary: "Record cash position and deleveraging track support credit improvement thesis." },
],
debtMaturities: {
items: [
{ year: "2028", amount: 600, desc: "6.125% Senior Notes due 2028" },
{ year: "2030", amount: 600, desc: "4.125% Senior Notes due 2030" },
],
},
},
{
id: "IHRT",
pm: "YP",
name: "iHeartMedia Inc.",
sector: "Media / Broadcasting",
exposure: 20000000,
sp: "CCC+",
moodys: "Caa2",
fitch: "NR",
impliedRating: "CCC",
outlook: "Negative",
watchlist: true,
cds5y: 2800,
cds5yChg: 150,
bondSpread: 1450,
bondSpreadChg: 85,
eqPrice: 1.22,
eqChg: -28.5,
mktCap: 0.18,
ltDebt: 4800,
totalDebt: 4800,
cash: 271,
ebitda: 768,
intExp: 440,
revenue: 3730,
netIncome: -320,
totalAssets: 9200,
totalEquity: -1600,
fcf: 138,
currentAssets: 1200,
currentLiab: 950,
grossLeverage: 6.3,
netLeverage: 5.9,
intCov: 1.7,
debtToEquity: -3.0,
currentRatio: 1.26,
roic: -3.5,
cashBurnQtr: 35,
liquidityRunway: "Tight — $640M total liquidity",
adjBurn: {
adjEBITDA: 768,
adjEBITDA_src: "FY2025 Earnings Release; consolidated adj EBITDA",
incomeTaxes: 15,
incomeTaxes_src: "Minimal cash taxes; NOL carryforwards from 2019 bankruptcy",
prefDividends: 0,
prefDividends_src: "No preferred stock",
maintCapex: 40,
totalCapex: 80,
totalCapex_src: "FY2025 estimated; technology + infrastructure maintenance",
currentLTD: 51,
currentLTD_src: "Term loans due 2026 ($5.1M + $1.5M) + 6.375% notes ($44.6M) — most exchanged Dec 2024",
intExpCash: 440,
intExpCash_src: "FY2025; weighted avg ~9% on ~$4.8B total debt",
},
liquidityBreakdown: {
totalLiquidity: 640,
components: [
{ category: "Cash & Cash Equivalents", amount: 271, type: "cash", sub: [
{ label: "Unrestricted Cash", amount: 271 },
]},
{ category: "Undrawn Credit Facilities", amount: 369, type: "facility", sub: [] },
],
facilities: [
{ name: "ABL Revolving Credit Facility", committed: 450, drawn: 81, available: 369, maturity: "2027", rate: "SOFR + spread", secured: "Senior Secured", notes: "Asset-based revolver; availability = cash + AR borrowing base; total liquidity $640M per Q4 2025 earnings release" },
],
debtMaturities: [
{ year: "2026", amount: 51, desc: "Remaining term loans + 6.375% notes not exchanged" },
{ year: "2027", amount: 79, desc: "5.25% secured notes ($7M) + 8.375% unsecured ($72M)" },
{ year: "2028", amount: 277, desc: "4.75% Senior Secured Notes" },
{ year: "2029", amount: 2858, desc: "Term Loan ($2,140M) + 9.125% 1L Notes ($718M)" },
{ year: "2030", amount: 1336, desc: "7.75% 1L Notes ($661M) + 10.875% 2L Notes ($675M)" },
{ year: "2031", amount: 178, desc: "7.00% First Lien Notes" },
{ year: "Other", amount: 0, desc: "" },
],
},
earningsDate: "2026-05-11",
earningsTime: "After Close",
lastEarnings: "Miss — adj. EBITDA $220M vs $246M prior yr",
earningsCallSummary: {
date: "March 2, 2026",
quarter: "Q4 FY2025",
source: "SEC Filing: Q4 FY2025 Earnings Release + Earnings Call",
keyFinancials: [
"Q4 consolidated revenue: results announced March 2, 2026",
"Q4 adjusted EBITDA $220M, down 10.5% YoY from $246M",
"Q4 operating income $86M, down 18% from $105M in Q4 2024",
"FY2025 GAAP operating loss of -$21M (improved from -$763M in 2024 which included $923M impairment)",
"Cash balance $271M, total liquidity $640M as of Dec 31, 2025",
],
production: [
"Q4 free cash flow of $138M; FCF including real estate sales of $158M",
"Cash provided by operating activities $156M in Q4",
"No. 1 audio company in America, reaching 250M+ people monthly",
],
creditRelevant: [
"Completed $4.8B comprehensive debt exchange in Dec 2024 — reduced total debt by $440M",
"Exchanged near-term maturities (2026-2028 notes) into new 2029-2031 first/second lien notes",
"Remaining debt stack: $2.14B Term Loan (2029), $718M 9.125% 1L (2029), $661M 7.75% 1L (2030), $178M 7.00% 1L (2031), $675M 10.875% 2L (2030)",
"Very high leverage at ~6.3x gross; interest coverage thin at 1.7x",
"Negative stockholders equity of -$1.6B reflects accumulated impairments",
],
strategicItems: [
"Digital revenue growth from podcasting and streaming platforms",
"iHeartPodcasts is #1 podcast publisher globally",
"Secular headwinds in traditional radio advertising",
"Focus on cost management and digital transformation",
],
analystQA: [
"Revenue outlook for Q1 2026? — Management provided Q1 2026 revenue and EBITDA guidance during earnings call",
"Debt sustainability? — Exchange transaction extended maturities but total burden remains very high at ~6x leverage",
],
},
analystRating: "Sell",
targetPrice: 2.50,
news: [
{ date: "2026-03-02", src: "Business Wire", headline: "iHeartMedia reports Q4/FY2025 results; adj EBITDA declines 10.5%", sentiment: "negative" },
{ date: "2025-12-22", src: "Reuters", headline: "iHeartMedia completes $4.8B debt restructuring, reduces debt by $440M", sentiment: "positive" },
{ date: "2025-11-10", src: "CNBC", headline: "iHeartMedia Q3 revenue flat as traditional radio ad spend stagnates", sentiment: "negative" },
],
ratingHistory: [
{ date: "2025-12", sp: "CCC+", moodys: "Caa2", fitch: "NR", event: "Completed $4.8B comprehensive debt exchange" },
{ date: "2024-11", sp: "CCC+", moodys: "Caa2", fitch: "NR", event: "Entered TSA with 80% of debt holders for exchange" },
],
financials: [
{ period: "FY2025", rev: 3730, ebitda: 768, ni: -320, debt: 4800, cash: 271 },
{ period: "FY2024", rev: 3800, ebitda: 820, ni: -714, debt: 5200, cash: 315 },
{ period: "FY2023", rev: 3820, ebitda: 845, ni: -175, debt: 5400, cash: 290 },
{ period: "FY2022", rev: 3960, ebitda: 880, ni: -210, debt: 5580, cash: 380 },
],
research: [
{ date: "2026-03-03", firm: "Wells Fargo", action: "Underweight", pt: 1.00, summary: "Leverage unsustainable at 6x+; radio ad market in structural decline; digital pivot insufficient." },
{ date: "2025-12-23", firm: "B. Riley", action: "Neutral", pt: 2.00, summary: "Debt exchange extends maturities but doesn't solve fundamental over-leverage problem." },
],
debtMaturities: {
items: [
{ year: "2029", amount: 2858, desc: "Term Loan ($2.14B) + 9.125% 1L Notes ($718M)" },
{ year: "2030", amount: 1336, desc: "7.75% 1L Notes ($661M) + 10.875% 2L Notes ($675M)" },
{ year: "2031", amount: 178, desc: "7.00% First Lien Notes" },
{ year: "Other", amount: 400, desc: "Remaining near-term maturities + ABL" },
],
},
},
{
id: "BEUSA",
pm: "YP",
name: "Beusa Investments LLC",
sector: "Energy / Oilfield Services",
exposure: 10000000,
sp: "NR",
moodys: "NR",
fitch: "NR",
impliedRating: "B-",
outlook: "Stable",
watchlist: true,
cds5y: null,
cds5yChg: null,
bondSpread: null,
bondSpreadChg: null,
eqPrice: null,
eqChg: null,
mktCap: null,
ltDebt: 200,
totalDebt: 200,
cash: 45,
ebitda: 55,
intExp: 20,
revenue: 250,
netIncome: 10,
totalAssets: 500,
totalEquity: 150,
fcf: 25,
currentAssets: 120,
currentLiab: 80,
grossLeverage: 3.6,
netLeverage: 2.8,
intCov: 2.8,
debtToEquity: 1.33,
currentRatio: 1.50,
roic: 5.0,
cashBurnQtr: 6,
liquidityRunway: "Private — limited visibility",
adjBurn: {
adjEBITDA: 55,
adjEBITDA_src: "Estimated from bank group information; private company",
incomeTaxes: 5,
incomeTaxes_src: "Estimated; pass-through entity structure likely",
prefDividends: 0,
prefDividends_src: "No preferred stock known",
maintCapex: 15,
totalCapex: 25,
totalCapex_src: "Estimated; equipment fleet maintenance + growth capex",
currentLTD: 10,
currentLTD_src: "Estimated current portion of equipment financing",
intExpCash: 20,
intExpCash_src: "Estimated; ~10% rate on $200M total debt",
},
liquidityBreakdown: {
totalLiquidity: 75,
components: [
{ category: "Cash & Cash Equivalents", amount: 45, type: "cash", sub: [
{ label: "Unrestricted Cash", amount: 45 },
]},
{ category: "Undrawn Credit Facilities", amount: 30, type: "facility", sub: [] },
],
facilities: [
{ name: "Revolving Credit Facility", committed: 50, drawn: 20, available: 30, maturity: "2027", rate: "SOFR + 3.50%", secured: "Senior Secured", notes: "Private — estimated from bank group data; asset-based facility secured by equipment" },
],
debtMaturities: [
{ year: "2026", amount: 10, desc: "Current portion of equipment term loans" },
{ year: "2027", amount: 60, desc: "Revolver maturity + equipment loans" },
{ year: "2028", amount: 80, desc: "Term loan facilities" },
{ year: "Other", amount: 50, desc: "Other secured obligations" },
],
},
earningsDate: null,
earningsTime: null,
lastEarnings: "Private — no public earnings",
earningsCallSummary: {
date: "N/A",
quarter: "Private Company",
source: "Private company — financials from bank group information package",
keyFinancials: [
"Private company — Beusa Holdings / Beusa Energy, The Woodlands, TX",
"Estimated revenue $100M-$250M based on industry data; exact figures from bank package only",
"Parent company of Evolution Well Services (electric frac) and Dynamis Power Solutions",
],
production: [
"Operations across Haynesville/Bossier (LA), Permian (TX/NM), Eagle Ford (TX), Marcellus/Utica (PA/OH)",
"Vertically integrated: E&P, electric frac (Evolution), turbine power (Dynamis), logistics",
"~140-200 employees across operations",
],
creditRelevant: [
"Private — limited financial transparency; rely on bank group reporting",
"Small-to-midsize oilfield services company with commodity exposure",
"Evolution Well Services is market leader in electric hydraulic fracturing — growing segment",
"Capital-intensive business model with equipment fleet financing needs",
],
strategicItems: [
"Electric frac technology differentiator — 100% electric equipment reduces emissions",
"Dynamis expanding into data center and grid stabilization power solutions",
"30-year operating history in energy sector",
],
analystQA: [],
},
analystRating: "NR",
targetPrice: null,
news: [
{ date: "2025-11-25", src: "Company", headline: "Beusa Energy rebrands, highlighting integrated energy solutions beyond oil & gas", sentiment: "positive" },
],
ratingHistory: [],
financials: [
{ period: "FY2025E", rev: 250, ebitda: 55, ni: 10, debt: 200, cash: 45 },
{ period: "FY2024E", rev: 220, ebitda: 48, ni: 5, debt: 210, cash: 35 },
],
research: [],
debtMaturities: { items: [] },
},
{
id: "SMC",
pm: "YP",
name: "Summit Midstream Corp.",
sector: "Midstream / Energy",
exposure: 12000000,
sp: "NR",
moodys: "NR",
fitch: "NR",
impliedRating: "B",
outlook: "Stable",
watchlist: true,
cds5y: 650,
cds5yChg: -25,
bondSpread: 520,
bondSpreadChg: -15,
eqPrice: 28.50,
eqChg: 3.7,
mktCap: 0.62,
ltDebt: 930,
totalDebt: 930,
cash: 21,
ebitda: 243,
intExp: 90,
revenue: 430,
netIncome: -25,
totalAssets: 2800,
totalEquity: 470,
fcf: 17,
currentAssets: 85,
currentLiab: 125,
grossLeverage: 3.8,
netLeverage: 3.7,
intCov: 2.7,
debtToEquity: 1.98,
currentRatio: 0.68,
roic: 3.5,
cashBurnQtr: 4,
liquidityRunway: "Adequate — $500M ABL + FCF",
adjBurn: {
adjEBITDA: 243,
adjEBITDA_src: "FY2025 Earnings Release; reported adj EBITDA $242.6M",
incomeTaxes: 5,
incomeTaxes_src: "FY2025 10-K; minimal cash taxes; NOL carryforwards",
prefDividends: 0,
prefDividends_src: "Series A preferred — accrued dividends, planning repayment",
maintCapex: 18,
totalCapex: 89,
totalCapex_src: "FY2025 actual $89M; includes $15-20M maintenance + growth connections",
currentLTD: 7,
currentLTD_src: "Remaining term loans due 2026 (~$7M)",
intExpCash: 90,
intExpCash_src: "FY2025; ~9.5% weighted avg on $930M total debt + Permian facility",
},
liquidityBreakdown: {
totalLiquidity: 458,
components: [
{ category: "Cash & Cash Equivalents", amount: 21, type: "cash", sub: [
{ label: "Unrestricted Cash", amount: 21 },
]},
{ category: "Undrawn Credit Facilities", amount: 437, type: "facility", sub: [] },
],
facilities: [
{ name: "ABL Revolving Credit Facility", committed: 500, drawn: 112, available: 387, maturity: "2028", rate: "SOFR + spread", secured: "Senior Secured", notes: "Gross availability $810M per borrowing base (exceeds $500M commitments); $112M drawn at year-end; $40M repayment planned from Double E distribution (pro forma ~$72M drawn); first lien leverage 0.5x vs 2.5x max covenant; $0.8M issued but undrawn LCs" },
{ name: "Permian Transmission Term Loan", committed: 440, drawn: 340, available: 50, maturity: "Mar 2031", rate: "SOFR + spread", secured: "Project Secured", notes: "New $440M facility (closed Mar 2026): $340M drawn at closing + $50M committed delayed draw for expansion + $50M accordion; replaced prior Permian facility ($112.7M balance) and subsidiary preferred equity" },
],
debtMaturities: [
{ year: "2026", amount: 7, desc: "Remaining term loans" },
{ year: "2027", amount: 7, desc: "5.25% Senior Secured Notes" },
{ year: "2028", amount: 389, desc: "4.75% Senior Secured Notes ($277M) + ABL drawn ($112M)" },
{ year: "2029", amount: 350, desc: "8.50% Senior Secured Notes" },
{ year: "2031", amount: 340, desc: "Permian Transmission Term Loan" },
{ year: "Other", amount: 250, desc: "Second Lien Notes + other" },
],
},
earningsDate: "2026-05-15",
earningsTime: "After Close",
lastEarnings: "In-line — adj EBITDA $58.6M (Q4)",
earningsCallSummary: {
date: "March 16, 2026",
quarter: "Q4 FY2025",
source: "SEC Filing: Q4 FY2025 Earnings Release + Earnings Call",
keyFinancials: [
"Q4 adjusted EBITDA $58.6M; FY2025 adjusted EBITDA $243M",
"Q4 distributable cash flow $33.7M; Q4 free cash flow $17.0M",
"FY2025 capex $89M ($19M in Q4); 2026 EBITDA guidance $225M-$265M",
"Net debt ~$930M at year-end; total leverage 4.1x (excl. Tall Oak earnout)",
],
production: [
"Average daily natural gas throughput increasing on wholly owned systems",
"Double E Pipeline signed three new 10+-year firm take-or-pay contracts",
"Launched binding open season on Double E to increase firm capacity by up to 50% to ~2.4 Bcf/d",
],
creditRelevant: [
"Total leverage 4.1x — elevated but improving; interest coverage 2.7x (covenant minimum 2.0x)",
"ABL Revolver: $500M committed, $810M gross availability; borrowing base well in excess",
"In compliance with all financial covenants as of Dec 31, 2025",
"First lien leverage 0.5x vs. 2.5x max covenant — significant headroom",
"Permian Transmission Credit Facility balance $112.7M, declining via scheduled payments",
],
strategicItems: [
"Double E pipeline driving Permian segment EBITDA growth from $34M (2025) to ~$60M target by 2029",
"New 10-year crude gathering contract in Divide County, ND (200K+ acres)",
"Piceance MVC payments declining from $17M (2025) to $13M (2026), rolling off fully in 2027",
"Planning to resume common stock dividend after Series A preferred repayment",
],
analystQA: [
"2026 EBITDA bridge? — CFO Mault: Guidance of $225M-$265M reflects customer development schedules and Double E contract ramps",
"Deleveraging timeline? — Management: Targeting further debt reduction through FCF; pro forma net debt ~$890M after $40M ABL repayment",
],
},
analystRating: "Hold",
targetPrice: 32.00,
news: [
{ date: "2026-03-16", src: "PR Newswire", headline: "Summit Midstream reports Q4/FY2025; signs new 10-year Double E contracts", sentiment: "positive" },
{ date: "2025-08-12", src: "SEC", headline: "Summit Midstream Q2 adj EBITDA $61.1M; expects FY near low end of guidance", sentiment: "negative" },
],
ratingHistory: [
{ date: "2025-01", sp: "NR", moodys: "NR", fitch: "NR", event: "$250M Second Lien add-on executed" },
{ date: "2024-10", sp: "NR", moodys: "NR", fitch: "NR", event: "Tall Oak Midstream III acquisition completed" },
],
financials: [
{ period: "FY2025", rev: 430, ebitda: 243, ni: -25, debt: 930, cash: 21 },
{ period: "FY2024", rev: 430, ebitda: 225, ni: -122, debt: 977, cash: 23 },
{ period: "FY2023", rev: 400, ebitda: 210, ni: -80, debt: 1050, cash: 18 },
],
research: [
{ date: "2026-03-17", firm: "Stifel", action: "Hold", pt: 30, summary: "Double E contract wins de-risk Permian growth; leverage still elevated at 4.1x but trajectory improving." },
],
debtMaturities: {
items: [
{ year: "2026", amount: 7, desc: "Remaining term loans due 2026" },
{ year: "2027", amount: 7, desc: "5.25% Senior Secured Notes" },
{ year: "2028", amount: 389, desc: "4.75% Senior Secured Notes + ABL drawn" },
{ year: "2029", amount: 350, desc: "8.50% Senior Secured Notes" },
{ year: "2031", amount: 340, desc: "Permian Transmission Term Loan" },
{ year: "Other", amount: 250, desc: "Second Lien Notes + other" },
],
},
},
{
id: "UPBD",
pm: "YP",
name: "Upbound Group Inc.",
sector: "Consumer Finance / RTO",
exposure: 18000000,
sp: "BB-",
moodys: "Ba3",
fitch: "NR",
impliedRating: "BB-",
outlook: "Stable",
watchlist: false,
cds5y: 380,
cds5yChg: 5,
bondSpread: 340,
bondSpreadChg: 10,
eqPrice: 19.30,
eqChg: -5.2,
mktCap: 1.12,
ltDebt: 1730,
totalDebt: 1730,
cash: 120,
ebitda: 500,
intExp: 115,
revenue: 4680,
netIncome: 130,
totalAssets: 5200,
totalEquity: 650,
fcf: 175,
currentAssets: 1800,
currentLiab: 720,
grossLeverage: 3.5,
netLeverage: 3.2,
intCov: 4.3,
debtToEquity: 2.66,
currentRatio: 2.50,
roic: 9.9,
cashBurnQtr: 44,
liquidityRunway: "Adequate — strong FCF generation",
adjBurn: {
adjEBITDA: 500,
adjEBITDA_src: "FY2025 guidance $500-$510M adj EBITDA excl. SBC",
incomeTaxes: 35,
incomeTaxes_src: "FY2025 estimated; ~22% effective on adjusted pre-tax",
prefDividends: 0,
prefDividends_src: "No preferred stock",
maintCapex: 30,
totalCapex: 50,
totalCapex_src: "FY2025 estimated; store maintenance + technology investment",
currentLTD: 45,
currentLTD_src: "Estimated current portion of term loan amortization",
intExpCash: 115,
intExpCash_src: "FY2025; ~6.7% weighted avg on $1.73B total debt",
},
liquidityBreakdown: {
totalLiquidity: 620,
components: [
{ category: "Cash & Cash Equivalents", amount: 120, type: "cash", sub: [
{ label: "Unrestricted Cash", amount: 120 },
]},
{ category: "Undrawn Credit Facilities", amount: 500, type: "facility", sub: [] },
],
facilities: [
{ name: "ABL Revolving Credit Facility", committed: 600, drawn: 100, available: 500, maturity: "2028", rate: "SOFR + spread", secured: "Senior Secured", notes: "Availability based on eligible lease receivables borrowing base; strong current ratio of 2.5x supports liquidity" },
],
debtMaturities: [
{ year: "2026", amount: 0, desc: "No maturities" },
{ year: "2027", amount: 0, desc: "No maturities" },
{ year: "2028", amount: 875, desc: "Term Loan B + Senior Secured Notes" },
{ year: "2029", amount: 500, desc: "Senior Unsecured Notes" },
{ year: "Other", amount: 355, desc: "ABL + other secured" },
],
},
earningsDate: "2026-04-30",
earningsTime: "Before Open",
lastEarnings: "Beat — non-GAAP EPS $1.00 vs $0.95 est.",
earningsCallSummary: {
date: "Q4 FY2025 (pending — not yet reported)",
quarter: "FY2025 Full Year",
source: "SEC Filings: Q1-Q3 FY2025 Earnings Releases",
keyFinancials: [
"Q3 FY2025 revenue $1,168M; FY2025 revenue guidance $4.60B-$4.75B",
"Q3 adj EBITDA $123.6M (up 5.7% YoY); FY2025 EBITDA guidance $500-$510M",
"Q3 non-GAAP diluted EPS $1.00 vs $0.95 prior year",
"2026 outlook: revenue $4.7B-$4.95B; adj EBITDA $500M-$535M",
],
production: [
"Acima (virtual lease-to-own): Growing GMV through retail partner expansion; rising LCO rates a concern",
"Rent-A-Center: Same-store sales stabilizing; company-owned SSS down 3.6% (improving sequentially)",
"Brigit (fintech acquisition Jan 2025): Subscription-based financial tools for underserved consumers",
"~1,800 Rent-A-Center store locations in US, Mexico, Puerto Rico",
],
creditRelevant: [
"Net leverage ~2.9x; within manageable range for BB-minus credit",
"Strong FCF generation ($150-$200M FY2025 guidance) supports deleveraging",
"Acima LCO (lease charge-off) rates trending — key credit metric; Q3 at 9.7%",
"High debt-to-equity at 2.67x reflects acquisition-related leverage (Acima, Brigit)",
"Current ratio strong at 2.5x — ample short-term liquidity",
],
strategicItems: [
"Omnichannel strategy: Acima (digital/virtual) + Rent-A-Center (stores) + Brigit (fintech)",
"Serving credit-constrained / non-prime consumers — counter-cyclical demand element",
"Fahmi Karam became CEO (previously CFO); focus on execution and shareholder value",
"Quarterly dividend of $0.39/share maintained",
],
analystQA: [
"Acima growth vs. credit quality? — Management: Tighter underwriting to manage LCO rates while growing retail partnerships",
"Leverage reduction path? — CFO: FCF of $150-200M annually; expect deleveraging from earnings growth rather than debt paydown",
],
},
analystRating: "Buy",
targetPrice: 22.00,
news: [
{ date: "2026-02-20", src: "Business Wire", headline: "Upbound posts strong FY2025 results; sets 2026 outlook for revenue growth and EBITDA expansion", sentiment: "positive" },
{ date: "2025-10-30", src: "Seeking Alpha", headline: "Upbound Q3: Acima LCO rates rising but non-GAAP EPS beats; EBITDA guidance lowered modestly", sentiment: "negative" },
{ date: "2025-05-01", src: "Business Wire", headline: "Upbound Q1 2025 revenue up 7.3% YoY; Brigit acquisition adding segment diversification", sentiment: "positive" },
],
ratingHistory: [
{ date: "2025-01", sp: "BB-", moodys: "Ba3", fitch: "NR", event: "Brigit fintech acquisition completed ($460M)" },
{ date: "2024-06", sp: "BB-", moodys: "Ba3", fitch: "NR", event: "Ratings affirmed with stable outlook" },
],
financials: [
{ period: "FY2025E", rev: 4680, ebitda: 500, ni: 130, debt: 1730, cash: 120 },
{ period: "FY2024", rev: 4320, ebitda: 455, ni: 121, debt: 1750, cash: 105 },
{ period: "FY2023", rev: 3990, ebitda: 420, ni: 95, debt: 1650, cash: 90 },
{ period: "FY2022", rev: 4300, ebitda: 475, ni: 185, debt: 1500, cash: 115 },
],
research: [
{ date: "2026-03-01", firm: "Loop Capital", action: "Buy", pt: 22, summary: "Acima growth + Brigit diversification underappreciated; 2026 EBITDA expansion should drive re-rating." },
{ date: "2025-12-15", firm: "Seeking Alpha", action: "Hold", pt: 18, summary: "Cheap valuation justified by elevated leverage, Acima credit stress, and store count headwinds." },
],
debtMaturities: {
items: [
{ year: "2028", amount: 875, desc: "Term Loan B + Senior Secured Notes" },
{ year: "2029", amount: 500, desc: "Senior Unsecured Notes" },
{ year: "Other", amount: 355, desc: "ABL + other secured facilities" },
],
},
},
{
id: "WSC",
pm: "YP",
name: "WillScot Holdings Corp.",
sector: "Industrial Services / Modular Space",
exposure: 22000000,
sp: "BB+",
moodys: "Ba2",
fitch: "NR",
impliedRating: "BB+",
outlook: "Stable",
watchlist: false,
cds5y: 220,
cds5yChg: -5,
bondSpread: 195,
bondSpreadChg: -3,
eqPrice: 29.15,
eqChg: -8.2,
mktCap: 5.4,
ltDebt: 3400,
totalDebt: 3400,
cash: 35,
ebitda: 971,
intExp: 218,
revenue: 2282,
netIncome: 134,
totalAssets: 13500,
totalEquity: 3200,
fcf: 450,
currentAssets: 520,
currentLiab: 680,
grossLeverage: 3.5,
netLeverage: 3.5,
intCov: 4.5,
debtToEquity: 1.06,
currentRatio: 0.76,
roic: 16.7,
cashBurnQtr: 112,
liquidityRunway: "Strong — $1.6B ABL availability",
adjBurn: {
adjEBITDA: 971,
adjEBITDA_src: "FY2025 Earnings Release; adj EBITDA ~$971M at 42.5% margin",
incomeTaxes: 50,
incomeTaxes_src: "FY2025 estimated; ~25% effective rate on adjusted pre-tax",
prefDividends: 0,
prefDividends_src: "No preferred stock",
maintCapex: 100,
totalCapex: 200,
totalCapex_src: "FY2025 net capex estimated; fleet maintenance + growth",
currentLTD: 50,
currentLTD_src: "Redeemed $50M of 7.375% 2031 notes in Q4 2025; ongoing amortization",
intExpCash: 218,
intExpCash_src: "FY2025; weighted avg ~5.7% after swaps on ~$3.4B debt; per Q3 2025 earnings",
},
liquidityBreakdown: {
totalLiquidity: 1635,
components: [
{ category: "Cash & Cash Equivalents", amount: 35, type: "cash", sub: [
{ label: "Unrestricted Cash", amount: 35 },
]},
{ category: "Undrawn Credit Facilities", amount: 1600, type: "facility", sub: [] },
],
facilities: [
{ name: "ABL Revolving Credit Facility", committed: 3600, drawn: 2000, available: 1600, maturity: "Oct 2030", rate: "SOFR + spread", secured: "Senior Secured", notes: "Amended Oct 2025 extending maturity to 2030; ~$5M annual interest savings; availability based on fleet asset borrowing base; 89% fixed after $1.25B swaps" },
],
debtMaturities: [
{ year: "2026", amount: 0, desc: "No maturities" },
{ year: "2027", amount: 0, desc: "No maturities" },
{ year: "2028", amount: 1000, desc: "Senior Secured Notes due 2028" },
{ year: "2029", amount: 900, desc: "Senior Secured Notes due 2029" },
{ year: "2030", amount: 1000, desc: "ABL Facility (maturity Oct 2030) + Notes" },
{ year: "2031", amount: 500, desc: "7.375% Senior Secured Notes (partially redeemed)" },
{ year: "Other", amount: 0, desc: "" },
],
},
earningsDate: "2026-05-07",
earningsTime: "Before Open",
lastEarnings: "Mixed — adj EBITDA $250M, net loss $187M (impairment)",
earningsCallSummary: {
date: "February 19, 2026",
quarter: "Q4 FY2025",
source: "SEC Filing: Q4 FY2025 Earnings Release + Press Release",
keyFinancials: [
"Q4 revenue $566M; FY2025 revenue ~$2,282M (down from $2,396M in FY2024)",
"Q4 adjusted EBITDA $250M (44.2% margin); FY2025 adj EBITDA ~$971M",
"Q4 net loss of -$187M due to non-cash impairment; adj net income $55M",
"FY2025 net income $134M; adj income ~$219M",
],
production: [
"Average modular space monthly rates up 5.2% YoY; portable storage rates up 1.9%",
"Units on rent declined slightly due to macro-related end-market softness",
"Pending order book up 7% YoY — supports new lease activations",
"2026 outlook: Revenue ~$2,225-$2,425M; Adj EBITDA ~$980-$1,080M",
],
creditRelevant: [
"Net Debt / adj EBITDA at 3.5x — within target range of 3.0-3.5x",
"Redeemed $50M of 7.375% 2031 notes using ABL to optimize interest costs",
"ABL Facility amended Oct 2025 — maturity extended to Oct 2030; ~$5M annual interest savings",
"ABL availability ~$1.6B; next debt maturity not until 2028",
"Weighted avg pre-tax interest rate ~5.7% (89% fixed after swaps)",
"Annual cash interest expense ~$218M",
],
strategicItems: [
"3-5 year financial milestones: $3B revenue, $1.5B adj EBITDA, $700M adj FCF",
"Value-added products and services (VAPS) driving rate expansion",
"Tuck-in acquisition pipeline progressing alongside organic growth",
"Returned $21M to shareholders in Q3 via buybacks and dividends",
],
analystQA: [
"Organic growth vs. M&A? — CEO Soultz: Multiple levers to achieve growth through different end-market backdrops; nimble approach",
"Leverage trajectory? — Management: Comfortable within 3.0-3.5x range; FCF generation and EBITDA growth support current levels",
],
},
analystRating: "Buy",
targetPrice: 38.00,
news: [
{ date: "2026-02-19", src: "Globe Newswire", headline: "WillScot reports Q4/FY2025 results; adj EBITDA margins resilient at 44%", sentiment: "positive" },
{ date: "2025-10-16", src: "Business Wire", headline: "WillScot amends ABL facility — extends maturity to 2030, reduces borrowing costs", sentiment: "positive" },
{ date: "2025-05-01", src: "Reuters", headline: "WillScot Q1 results in-line; reaffirms FY2025 outlook; pending order book up 7%", sentiment: "positive" },
],
ratingHistory: [
{ date: "2025-10", sp: "BB+", moodys: "Ba2", fitch: "NR", event: "ABL maturity extended to 2030; stable outlook maintained" },
{ date: "2025-03", sp: "BB+", moodys: "Ba2", fitch: "NR", event: "Investor Day: 3-5 year targets of $3B rev, $1.5B EBITDA, $700M adj FCF" },
],
financials: [
{ period: "FY2025", rev: 2282, ebitda: 971, ni: 134, debt: 3400, cash: 35 },
{ period: "FY2024", rev: 2396, ebitda: 1063, ni: 28, debt: 3500, cash: 40 },
{ period: "FY2023", rev: 2365, ebitda: 1061, ni: 342, debt: 3400, cash: 45 },
{ period: "FY2022", rev: 2140, ebitda: 930, ni: 290, debt: 3200, cash: 50 },
],
research: [
{ date: "2026-02-20", firm: "RBC Capital", action: "Outperform", pt: 40, summary: "Recurring revenue model provides stability; pricing power + VAPS penetration support margin expansion path." },
{ date: "2025-10-17", firm: "Morgan Stanley", action: "Overweight", pt: 42, summary: "ABL refinancing positive; 3-5 year targets ambitious but achievable given track record." },
],
debtMaturities: {
items: [
{ year: "2028", amount: 1000, desc: "Senior Secured Notes due 2028" },
{ year: "2029", amount: 900, desc: "Senior Secured Notes due 2029" },
{ year: "2030", amount: 1000, desc: "ABL Facility (extended Oct 2030) + Notes" },
{ year: "2031", amount: 500, desc: "7.375% Senior Secured Notes (partially redeemed)" },
],
},
},
{
id: "JSWUSA",
pm: "YP",
name: "JSW Steel USA Inc.",
sector: "Steel / Metals",
exposure: 8000000,
sp: "NR",
moodys: "NR",
fitch: "NR",
impliedRating: "BB-",
outlook: "Stable",
watchlist: true,
cds5y: null,
cds5yChg: null,
bondSpread: null,
bondSpreadChg: null,
eqPrice: null,
eqChg: null,
mktCap: null,
ltDebt: 350,
totalDebt: 350,
cash: 60,
ebitda: 85,
intExp: 22,
revenue: 1200,
netIncome: 25,
totalAssets: 1100,
totalEquity: 400,
fcf: 30,
currentAssets: 350,
currentLiab: 250,
grossLeverage: 4.1,
netLeverage: 3.4,
intCov: 3.9,
debtToEquity: 0.88,
currentRatio: 1.40,
roic: 5.5,
cashBurnQtr: 21,
liquidityRunway: "Backed by JSW Group ($24B parent)",
adjBurn: {
adjEBITDA: 85,
adjEBITDA_src: "Estimated from parent disclosures; US operations profitable at operating level per JSW Steel FY24-25 filings",
incomeTaxes: 8,
incomeTaxes_src: "Estimated; US federal + Ohio state taxes",
prefDividends: 0,
prefDividends_src: "No preferred stock; subsidiary of JSW Steel Ltd",
maintCapex: 20,
totalCapex: 40,
totalCapex_src: "Estimated; ongoing EAF modernization + rolling mill upgrades",
currentLTD: 15,
currentLTD_src: "Estimated current portion of conduit revenue bonds + working capital facilities",
intExpCash: 22,
intExpCash_src: "Estimated; ~6% on $350M debt including conduit bonds",
},
liquidityBreakdown: {
totalLiquidity: 120,
components: [
{ category: "Cash & Cash Equivalents", amount: 60, type: "cash", sub: [
{ label: "Unrestricted Cash", amount: 55 },
{ label: "Restricted Cash (bond proceeds)", amount: 5 },
]},
{ category: "Undrawn Credit Facilities", amount: 60, type: "facility", sub: [] },
],
facilities: [
{ name: "Working Capital Facility", committed: 75, drawn: 15, available: 60, maturity: "2027", rate: "SOFR + 2.50%", secured: "Senior Secured", notes: "Secured by inventory and receivables; parent JSW Group implicit backstop" },
],
debtMaturities: [
{ year: "2026", amount: 15, desc: "Current portion of term facilities" },
{ year: "2027", amount: 25, desc: "Working capital facility maturity" },
{ year: "2028", amount: 160, desc: "Tax-exempt conduit revenue bonds (Jefferson County Port Authority)" },
{ year: "Other", amount: 150, desc: "Parent-backed facilities + other" },
],
},
earningsDate: null,
earningsTime: null,
lastEarnings: "Private — parent JSW Steel FY25 reported",
earningsCallSummary: {
date: "N/A",
quarter: "Private Subsidiary",
source: "Private subsidiary of JSW Steel Limited (India) — financials from bank group / parent disclosures",
keyFinancials: [
"Private US subsidiary of JSW Group ($24B Indian conglomerate)",
"Estimated US revenue ~$1.2B across Ohio (Mingo Junction) and Texas (Baytown) operations",
"Parent JSW Steel reported consolidated net debt of INR 76,563 crores (~$9.1B) as of March 2025",
"Parent leverage improved — net debt/EBITDA declining on healthy cash generation",
],
production: [
"Two US locations: Mingo Junction, OH (EAF + slab caster + 80\" hot rolling mill) and Baytown, TX (plate mill)",
"Ohio facility acquired 2018 for ~$81M; invested $119M+ in modernization",
"Produces hot rolled coil (HRC) and plate for energy, infrastructure, and renewable sectors",
"Largest and most modern Consteel EAF technology in North America",
],
creditRelevant: [
"Private — limited standalone financial transparency; rely on bank group reporting",
"Implicit parent support from JSW Steel Ltd (India) — one of India's largest steelmakers",
"US operations profitable at operating level per parent disclosures (FY2023-2024)",
"Cyclical steel industry exposure — margins sensitive to scrap prices and HRC/plate spreads",
"$160M in tax-exempt conduit revenue bonds issued via Jefferson County Port Authority for plant upgrades",
],
strategicItems: [
"Growing focus on 'melted and manufactured in USA' products for infrastructure and renewable energy",
"ESG differentiator: Consteel EAF technology produces among the cleanest steel globally",
"Parent JSW Group has 29.7 MTPA installed capacity worldwide; global scale advantage",
"Potential beneficiary of US infrastructure spending and domestic steel tariff protection",
],
analystQA: [],
},
analystRating: "NR",
targetPrice: null,
news: [
{ date: "2025-05-05", src: "Recycling Today", headline: "JSW Steel USA plans $119M+ investment in Ohio EAF mill for renewable energy steel", sentiment: "positive" },
{ date: "2025-03-15", src: "JSW Group", headline: "Parent JSW Steel FY25: net debt declined; healthy domestic demand in India supports operations", sentiment: "positive" },
],
ratingHistory: [],
financials: [
{ period: "FY2025E", rev: 1200, ebitda: 85, ni: 25, debt: 350, cash: 60 },
{ period: "FY2024E", rev: 1100, ebitda: 72, ni: 15, debt: 320, cash: 50 },
{ period: "FY2023E", rev: 950, ebitda: 60, ni: 8, debt: 280, cash: 40 },
],
research: [],
debtMaturities: {
items: [
{ year: "2028", amount: 160, desc: "Tax-exempt conduit revenue bonds (Jefferson County Port Authority)" },
{ year: "Other", amount: 190, desc: "Working capital + parent-backed facilities" },
],
},
},
];

// ─── CREDIT AGREEMENT SUMMARIES ──────────────────────────────────────────
export const CREDIT_AGREEMENTS = {
LCID: {
facilityName: "ABL Credit Facility",
agent: "Bank of America, N.A.",
syndicate: "Citi, Barclays, Goldman Sachs, JPMorgan, BNP Paribas, RBC, HSBC, MUFG, SMBC, Wells Fargo",
committed: 1000, accordion: 500, maturity: "June 9, 2027",
lcSublimit: 350, swinglineSublimit: 100,
borrowingBase: "Eligible borrowing base assets (receivables, inventory, and other eligible assets), subject to reserves. Availability is less than full commitment — currently only a portion of the $1.0B is accessible based on borrowing base value.",
bbFormula: "Lesser of (a) Aggregate Commitments and (b) BB = [Eligible Receivables x advance rate] + [Eligible Inventory x advance rate] + [Other Eligible Assets] - Reserves",
bbComponents: [
{ category: "Eligible Receivables", advanceRate: "85%", description: "Trade receivables from vehicle sales, service, and fleet customers (net of dilution, ineligibles, and concentration limits)", source: "10-K FY2024; ABL Credit Agreement" },
{ category: "Eligible Inventory", advanceRate: "65% of NOLV", description: "Finished vehicles, work-in-process, and raw materials valued at lower of cost or net orderly liquidation value (NOLV). Excludes consignment, slow-moving (>180 days), and located outside US/Canada.", source: "ABL Credit Agreement (Jun 2022)" },
{ category: "Other Eligible Assets", advanceRate: "Varies", description: "Qualified cash in deposit accounts (capped); eligible tooling or other assets per agent discretion", source: "ABL Credit Agreement" },
{ category: "Reserves", advanceRate: "N/A (deducted)", description: "Rent reserves, dilution reserves, IP reserves, availability block ($50M), environmental reserves, landlord/warehouseman reserves, priority claims", source: "ABL Credit Agreement" },
],
bbAvailCalc: { grossBB: "~$650M (estimated)", lessReserves: "~$253M", netAvailability: "$397M", excessAvailability: "$397M (no draws outstanding)", trigger: "Springing FCCR triggered if excess availability < greater of $100M and 10% of Line Cap" },
pricing: "SOFR + applicable margin (based on avg. excess availability); or Base Rate + applicable margin",
pricingGrid: [
{ level: "Level I", condition: "Avg. Excess Availability >= 66.67% of Line Cap", sofrSpread: "1.50%", baseRateSpread: "0.50%", unusedFee: "0.250%" },
{ level: "Level II", condition: "Avg. Excess Availability >= 33.33% and < 66.67% of Line Cap", sofrSpread: "1.75%", baseRateSpread: "0.75%", unusedFee: "0.375%" },
{ level: "Level III", condition: "Avg. Excess Availability < 33.33% of Line Cap", sofrSpread: "2.00%", baseRateSpread: "1.00%", unusedFee: "0.375%" },
],
pricingNotes: "SOFR includes 10 bps credit spread adjustment (CSA). Floor: 0%. Current level: Level I (facility fully undrawn). LC fee equal to applicable SOFR margin. Fronting fee: 0.125% per annum.",
security: "First-priority perfected security interest in substantially all assets of Loan Parties, excluding intellectual property",
securityDetail: {
pledgedAssets: [
"All accounts receivable, payment intangibles, and instruments",
"All inventory (raw materials, WIP, finished goods)",
"All deposit accounts and securities accounts (subject to control agreements)",
"All equipment (excluding leased equipment and IP-related assets)",
"All general intangibles (excluding intellectual property)",
"All documents, chattel paper, letter-of-credit rights",
"100% of equity interests in domestic subsidiaries; 65% of first-tier foreign subsidiaries",
],
excludedAssets: [
"Intellectual property (patents, trademarks, copyrights) — separate IP security agreement may apply",
"Real property (no mortgage requirement under ABL)",
"Leasehold interests (excluded except as to proceeds)",
"Assets subject to permitted liens or contractual anti-assignment clauses",
],
intercreditorNotes: "ABL has first-priority lien on ABL Priority Collateral (receivables, inventory, deposit accounts). DDTL (PIF) and SIDF are structurally separate and do not share ABL collateral pool. No intercreditor agreement required as DDTL is unsecured from ABL's collateral base.",
controlAgreements: "Deposit account control agreements (DACAs) required for all material bank accounts",
},
financialCovenants: [
{ covenant: "Minimum Liquidity", test: "$1.0B at all times", status: "Active", notes: "Pre-FCCR Covenant Trigger Date; falls away if FCCR > 1.00x for 2 consecutive quarters and Company elects to trigger" },
{ covenant: "Springing FCCR", test: "1.00:1.00 minimum", status: "Not yet triggered", notes: "Only effective after Company elects FCCR Covenant Trigger Date" },
],
negativeCov: "Restrictions on: additional indebtedness, liens, investments, restricted payments, asset sales, affiliate transactions; subject to customary baskets and exceptions",
availCurrent: 397, drawnCurrent: 0,
covenantCompliance: "In compliance as of Dec 31, 2025",
otherFacilities: "$2.0B DDTL (PIF — requires no ABL availability); SIDF $665M; GIB ~$266M",
src: "8-K (Jun 2022); 10-K FY2024; Q2 FY2025 10-Q",
},
RIVN: {
facilityName: "ABL Revolving Credit Facility (A&R)",
agent: "JPMorgan Chase Bank, N.A.",
syndicate: "JPMorgan-led syndicate",
committed: 1500, accordion: 0, maturity: "April 19, 2028",
lcSublimit: 1000, swinglineSublimit: 0,
borrowingBase: "Availability = lesser of borrowing base and $1.5B committed cap, reduced by borrowings and outstanding LCs.",
bbFormula: "Lesser of (a) $1,500M Cap and (b) BB - Outstanding Borrowings - Outstanding LCs",
bbComponents: [
{ category: "Eligible Receivables", advanceRate: "85%", description: "Vehicle trade receivables, fleet/commercial receivables. Net of dilution, aging >90 days, concentration limits (single debtor cap), and government contract receivables", source: "A&R ABL Agreement (Apr 2023)" },
{ category: "Eligible Inventory", advanceRate: "70% of NOLV", description: "Finished vehicles (R1T, R1S, delivery vans), components, and raw materials. Appraised periodically by independent firm. Excludes demo units, damaged/returned vehicles, and inventory >365 days.", source: "A&R ABL Agreement" },
{ category: "Eligible In-Transit Inventory", advanceRate: "50%", description: "Vehicles and parts in transit with proper documentation (bills of lading, insurance certificates)", source: "A&R ABL Agreement" },
{ category: "Reserves", advanceRate: "N/A (deducted)", description: "Rent reserves, warranty reserves, dilution reserves, availability block, recall-related reserves, priority payable reserves", source: "A&R ABL Agreement" },
],
bbAvailCalc: { grossBB: "~$1,200M (estimated)", lessReserves: "~$692M", netAvailability: "$508M", excessAvailability: "$508M (no draws outstanding)", trigger: "Springing FCCR triggered if excess availability < greater of $150M and 10% of Line Cap" },
pricing: "SOFR + applicable margin; or Base Rate + margin (adjusted quarterly based on avg. excess availability)",
pricingGrid: [
{ level: "Level I", condition: "Avg. Excess Availability >= 66.67% of Commitments", sofrSpread: "1.50%", baseRateSpread: "0.50%", unusedFee: "0.250%" },
{ level: "Level II", condition: "Avg. Excess Availability >= 33.33% and < 66.67%", sofrSpread: "1.75%", baseRateSpread: "0.75%", unusedFee: "0.375%" },
{ level: "Level III", condition: "Avg. Excess Availability < 33.33% of Commitments", sofrSpread: "2.00%", baseRateSpread: "1.00%", unusedFee: "0.500%" },
],
pricingNotes: "SOFR includes 10 bps CSA. Floor: 0%. LC participation fee equal to applicable SOFR margin. Current level: Level I. Facility undrawn; LCs outstanding: ~$992M (primarily for DOE ATVM support).",
security: "First-priority lien on ABL Priority Collateral (inventory, receivables, deposit accounts). Second-priority on Green Note collateral.",
securityDetail: {
pledgedAssets: [
"All accounts receivable and payment intangibles",
"All inventory (finished vehicles, components, raw materials, in-transit)",
"All deposit accounts and securities accounts (subject to DACAs)",
"All equipment located at Normal, IL plant and other owned facilities",
"All general intangibles (excluding core IP)",
"100% equity in domestic subsidiaries; 65% of first-tier foreign subs",
"All commercial tort claims above threshold",
],
excludedAssets: [
"Core intellectual property (EV platform, software, autonomous driving IP)",
"Real property interests at Normal, IL facility (separate mortgage for Green Notes)",
"Joint venture interests (VW JV excluded from collateral pool)",
"Assets subject to DOE ATVM loan covenants and restrictions",
],
intercreditorNotes: "ABL-Green Notes Intercreditor Agreement: ABL has first priority on ABL Priority Collateral (receivables, inventory, deposits); Green Notes have first priority on real property, equipment, IP. Each has second priority on the other's primary collateral. Separate collateral agent for each facility.",
controlAgreements: "DACAs on all material deposit accounts. Securities account control agreements for investment accounts. Springing cash dominion when excess availability falls below trigger threshold.",
},
financialCovenants: [
{ covenant: "Minimum Liquidity", test: "$1.0B at all times", status: "Active", notes: "Falls away upon FCCR > 1.0x for 2 consecutive quarters" },
],
negativeCov: "Customary: restrictions on additional debt, liens, investments, restricted payments, asset sales, affiliate transactions",
availCurrent: 508, drawnCurrent: 0,
covenantCompliance: "In compliance as of Dec 31, 2025",
otherFacilities: "DOE ATVM: up to $6.6B (conditional); VW JV: $2.0B expected 2026",
src: "8-K (Apr 2023); 10-Q Q3 FY2025; Q4 FY2025 Earnings",
},
CENT: {
facilityName: "Fourth A&R ABL Credit Facility",
agent: "Truist Bank",
syndicate: "Truist-led syndicate",
committed: 600, accordion: 400, maturity: "November 7, 2030",
lcSublimit: 50, swinglineSublimit: 75,
borrowingBase: "Eligible receivables, inventory, and at Company's election eligible real property, minus reserves.",
bbFormula: "BB = [Eligible A/R x advance rate] + [Eligible Inventory x advance rate] + [Elected Real Property] - Reserves",
bbComponents: [
{ category: "Eligible Receivables", advanceRate: "85%", description: "Trade receivables from garden and pet product sales to national retailers, distributors, and independents. Net of dilution (3-year avg), cross-aging (>25% past due), concentration limits (Home Depot, Walmart, Lowe's caps), and foreign receivables", source: "Fourth A&R ABL Agreement (Nov 2025)" },
{ category: "Eligible Inventory", advanceRate: "70% of NOLV (cost)", description: "Garden products (live goods at lower rate ~50%, hardlines, controls) and pet products (branded consumables, durables). Appraised annually by independent firm. Excludes seasonal excess (>12 months aged), consignment, and in-transit without insurance.", source: "Fourth A&R ABL Agreement" },
{ category: "Elected Real Property", advanceRate: "50% of appraised FMV", description: "Company may elect to include owned distribution centers and manufacturing facilities in the borrowing base. Requires mortgage filing and environmental assessment. Currently not elected (sufficient availability without).", source: "Fourth A&R ABL Agreement" },
{ category: "Reserves", advanceRate: "N/A (deducted)", description: "Customer rebate/promotional reserves, seasonal accrual reserves, rent reserves for leased distribution centers, dilution reserves, environmental reserves for garden chemical products", source: "Fourth A&R ABL Agreement" },
],
bbAvailCalc: { grossBB: "~$750M (estimated)", lessReserves: "~$150M", netAvailability: "$600M", excessAvailability: "$600M (fully undrawn)", trigger: "Springing FCCR triggered if excess availability < greater of $45M and 7.5% of Line Cap" },
pricing: "SOFR (floor 0%) + margin (1.00%-1.50% based on avg. availability); Base Rate + margin (0.00%-0.50%). Unused fee: tiered based on utilization.",
pricingGrid: [
{ level: "Level I", condition: "Avg. Excess Availability >= 66.67% of Line Cap", sofrSpread: "1.00%", baseRateSpread: "0.00%", unusedFee: "0.200%" },
{ level: "Level II", condition: "Avg. Excess Availability >= 33.33% and < 66.67%", sofrSpread: "1.25%", baseRateSpread: "0.25%", unusedFee: "0.250%" },
{ level: "Level III", condition: "Avg. Excess Availability < 33.33% of Line Cap", sofrSpread: "1.50%", baseRateSpread: "0.50%", unusedFee: "0.375%" },
],
pricingNotes: "SOFR includes 10 bps CSA. Floor: 0%. Current level: Level I (fully undrawn). LC fee equal to applicable SOFR margin. Fronting fee: 0.125%. Seasonal borrowings typically peak in Q1 (garden season inventory build).",
security: "Substantially all assets, including pledges of domestic and certain foreign subsidiary equity",
securityDetail: {
pledgedAssets: [
"All accounts receivable and payment intangibles from garden and pet product sales",
"All inventory (finished goods, raw materials, packaging) across distribution network",
"All deposit accounts and securities accounts (subject to DACAs)",
"All equipment at manufacturing and distribution facilities",
"All general intangibles (excluding core trademarks per separate IP agreement)",
"100% equity in domestic subsidiaries; 65% of first-tier foreign subsidiaries (UK, Canada)",
"All proceeds of the foregoing",
],
excludedAssets: [
"Real property (unless elected into borrowing base with mortgage)",
"Intellectual property subject to separate trademark security agreement",
"Foreign subsidiary assets beyond equity pledges",
"De minimis personal property below $1M threshold",
],
intercreditorNotes: "No intercreditor complexity. ABL is the sole secured facility. Senior Notes ($500M 4.125% 2030 and $500M 4.125% 2031) are unsecured senior obligations. Clean capital structure with ABL on top.",
controlAgreements: "DACAs on all material domestic deposit accounts. Cash dominion triggered when excess availability < $60M for 5 consecutive business days (or event of default).",
},
financialCovenants: [
{ covenant: "Springing FCCR", test: "1.00:1.00 minimum", status: "Not triggered", notes: "Triggered only when availability falls below specified threshold" },
],
negativeCov: "Customary ABL covenants: restrictions on debt, liens, investments, restricted payments, asset sales, affiliate transactions",
availCurrent: 600, drawnCurrent: 0,
covenantCompliance: "In compliance; fully undrawn at closing (Nov 2025)",
otherFacilities: "Senior Notes: 4.125% due 2030, 4.125% due 2031",
src: "8-K (Nov 7, 2025); 10-K FY2023",
},
IHRT: {
facilityName: "New ABL Facility",
agent: "Bank of America, N.A.",
syndicate: "BofA-led syndicate (refinanced May 2022)",
committed: 450, accordion: 150, maturity: "May 2027",
lcSublimit: 450, swinglineSublimit: 0,
borrowingBase: "90% of eligible A/R + 100% of qualified cash (capped at 5% of BB for trigger calcs), minus availability reserves.",
bbFormula: "BB = [90% x Eligible A/R] + [100% x Qualified Cash (max 5% of BB for triggers)] - Availability Reserves",
bbComponents: [
{ category: "Eligible Receivables", advanceRate: "90%", description: "Advertising receivables from national, regional, and digital sales. Subject to: 90-day aging cutoff, cross-aging (>50% past due), debtor concentration limits (no single advertiser >10%), credit insurance adjustments, and agency commission netting", source: "ABL Credit Agreement (May 2019, as amended May 2022)" },
{ category: "Qualified Cash", advanceRate: "100% (capped)", description: "Cash in controlled deposit accounts at BofA or approved banks. Capped at lesser of (a) actual qualified cash and (b) 5% of borrowing base for purposes of availability trigger calculations. Provides incremental liquidity support.", source: "ABL Credit Agreement" },
{ category: "Reserves", advanceRate: "N/A (deducted)", description: "Professional fee reserves, priority claims reserves (taxes, wages), rent reserves for leased tower/studio sites, dilution reserves (3-year avg dilution rate), music royalty accrual reserves (ASCAP/BMI/SESAC), environmental reserves for tower sites", source: "ABL Credit Agreement" },
],
bbAvailCalc: { grossBB: "~$500M (estimated)", lessReserves: "~$75M", netAvailability: "$425M", excessAvailability: "$425M (no principal drawn; ~$25M LCs outstanding)", trigger: "Springing FCCR/Cash Dominion triggered if availability < greater of $40M and 10% of aggregate commitments ($45M)" },
pricing: "SOFR (+ 10 bps CSA) + applicable margin; or Base Rate + margin; or Eurocurrency rate for foreign currencies",
pricingGrid: [
{ level: "Level I", condition: "Avg. Excess Availability >= 66.67% of Line Cap", sofrSpread: "1.75%", baseRateSpread: "0.75%", unusedFee: "0.250%" },
{ level: "Level II", condition: "Avg. Excess Availability >= 33.33% and < 66.67%", sofrSpread: "2.00%", baseRateSpread: "1.00%", unusedFee: "0.375%" },
{ level: "Level III", condition: "Avg. Excess Availability < 33.33% of Line Cap", sofrSpread: "2.25%", baseRateSpread: "1.25%", unusedFee: "0.375%" },
],
pricingNotes: "SOFR includes 10 bps CSA. Floor: 0%. Current level: Level I. Higher base spreads reflect CCC credit profile and post-emergence capital structure. LC fee: applicable SOFR margin. Fronting fee: 0.125%. Eurocurrency rate option available for foreign-currency denominated borrowings.",
security: "First-priority lien on substantially all assets of iHeartCommunications and subsidiary guarantors",
securityDetail: {
pledgedAssets: [
"All accounts receivable from advertising sales (national, regional, digital, podcast)",
"All deposit accounts and securities accounts (subject to DACAs)",
"All equipment (broadcast equipment, studio equipment, digital infrastructure)",
"All FCC broadcast licenses (to extent permitted by FCC regulations — lien attaches to economic value/proceeds, not the license itself)",
"All general intangibles including advertiser contracts and programming rights",
"100% equity in domestic subsidiaries; 65% of first-tier foreign subsidiaries",
"All intellectual property (iHeartRadio brand, podcast IP, digital platform)",
],
excludedAssets: [
"FCC broadcast licenses (lien on proceeds only per FCC rules — no direct pledge)",
"Real property (tower sites primarily leased; no mortgage requirement)",
"Assets of unrestricted subsidiaries (if any designated)",
"Equity interests in certain immaterial subsidiaries below $5M threshold",
],
intercreditorNotes: "Complex capital structure with multiple tranches. ABL has first priority on current assets (receivables, cash, inventory). Term Loan ($2.58B) and Senior Secured Notes share first-priority lien on fixed assets and IP via pari passu intercreditor agreement. Senior Unsecured Notes (4.75% 2028) are structurally subordinated. Waterfall: ABL > Sr Sec TL / Sr Sec Notes (pari passu) > Sr Unsec Notes.",
controlAgreements: "DACAs on all material bank accounts. Cash Dominion (mandatory sweep) triggered when availability falls below greater of $40M and 10% of commitments. All collections swept to ABL agent concentration account during Cash Dominion period.",
},
financialCovenants: [
{ covenant: "Springing FCCR", test: "1.00:1.00 minimum", status: "Not triggered", notes: "Triggered when availability < greater of (a) $40M and (b) 10% of aggregate commitments" },
{ covenant: "Cash Dominion", test: "Triggered at low availability", status: "Not triggered", notes: "Requires sweep of collections to pay down revolver when availability below threshold" },
],
negativeCov: "Restrictions on: additional indebtedness, liens, investments, restricted payments, asset sales, sale-leasebacks, mergers, affiliate transactions",
availCurrent: 425, drawnCurrent: 0,
covenantCompliance: "In compliance; no principal drawn (LCs: ~$25M outstanding)",
otherFacilities: "Term Loan ~$2.58B (2029); 5.25% Sr Sec Notes (2027); 8.375% Sr Sec Notes (2027); 4.75% Sr Unsec Notes (2028)",
src: "8-K (May 2022); 10-K FY2022; ABL Credit Agreement (May 2019, as amended)",
},
SMC: {
facilityName: "ABL Revolving Credit Facility",
agent: "Syndicate-led",
syndicate: "Bank syndicate",
committed: 500, accordion: 0, maturity: "2028",
lcSublimit: 0, swinglineSublimit: 0,
borrowingBase: "Gross availability $810M per borrowing base (exceeds $500M commitment cap). Availability limited by committed amount.",
bbFormula: "Lesser of (a) $500M Cap and (b) BB - Outstanding Borrowings - Outstanding LCs",
bbComponents: [
{ category: "Proved Reserves (PDP)", advanceRate: "65% of PV-10", description: "Proved developed producing reserves valued at PV-10 (SEC pricing). Primarily natural gas gathering and processing assets with long-lived reserve profiles. Redetermination semi-annually (April/October).", source: "ABL Credit Agreement; Reserve Engineer Reports" },
{ category: "Midstream Contracts", advanceRate: "Varies by tenor", description: "Value attributed to long-term gas gathering, processing, and transportation agreements with minimum volume commitments (MVCs). Contracts with investment-grade counterparties receive higher advance rates. Weighted by remaining contract life.", source: "ABL Credit Agreement" },
{ category: "Eligible Receivables", advanceRate: "85%", description: "Trade receivables from gathering, processing, and transportation fees. Subject to counterparty concentration limits and aging requirements (<60 days)", source: "ABL Credit Agreement" },
{ category: "Reserves", advanceRate: "N/A (deducted)", description: "Hedging reserves, environmental reserves (plugging and abandonment obligations), operational reserves, priority claims", source: "ABL Credit Agreement" },
],
bbAvailCalc: { grossBB: "$810M (per borrowing base)", lessReserves: "~$310M (reserves + capacity cap)", netAvailability: "$500M (capped by commitment)", excessAvailability: "$387M ($500M - $112M drawn)", trigger: "Financial maintenance covenants tested quarterly (not availability-based springing)" },
pricing: "SOFR + applicable spread",
pricingGrid: [
{ level: "Level I", condition: "Total Leverage Ratio <= 3.5x", sofrSpread: "2.25%", baseRateSpread: "1.25%", unusedFee: "0.375%" },
{ level: "Level II", condition: "Total Leverage Ratio > 3.5x and <= 4.5x", sofrSpread: "2.50%", baseRateSpread: "1.50%", unusedFee: "0.375%" },
{ level: "Level III", condition: "Total Leverage Ratio > 4.5x", sofrSpread: "2.75%", baseRateSpread: "1.75%", unusedFee: "0.500%" },
],
pricingNotes: "SOFR floor: 0%. Current level: Level I (leverage ~2.5x). Pricing grid based on total leverage ratio (not availability). Reflects midstream credit profile with stable cash flows from fee-based contracts.",
security: "Senior Secured — first priority lien on midstream assets",
securityDetail: {
pledgedAssets: [
"All gathering systems, pipelines, and compression facilities",
"All processing plants and related equipment",
"All rights-of-way, easements, and permits for pipeline corridors",
"All gas gathering and processing contracts (minimum volume commitments)",
"All accounts receivable from gathering and processing services",
"All deposit accounts and securities accounts",
"100% equity in all domestic subsidiaries (operating partnerships)",
"All hedging agreements and related collateral",
],
excludedAssets: [
"Permian Transmission JV assets (separately financed with $440M term loan)",
"Assets of unrestricted subsidiaries",
"De minimis assets below $500K threshold",
],
intercreditorNotes: "Multiple secured tranches: ABL has first priority on current assets and deposit accounts. Permian Transmission Term Loan ($440M, 2031) is project-financed, secured solely by Permian Transmission assets — ring-fenced. Senior Secured Notes (5.25% 2027, 4.75% 2028, 8.50% 2029) share pari passu lien on operating assets with ABL (with ABL having super-priority on revolving collateral). Second Lien Notes are structurally subordinated.",
controlAgreements: "DACAs on material accounts. Revenue sweep mechanism under certain leverage conditions.",
},
financialCovenants: [
{ covenant: "Min. Interest Coverage", test: "2.0x minimum", status: "Pass (2.7x actual)", notes: "Tested periodically; significant headroom" },
{ covenant: "Max. First Lien Leverage", test: "2.5x maximum", status: "Pass (0.5x actual)", notes: "Well within covenant; substantial headroom" },
],
negativeCov: "Customary restrictions on additional debt, liens, investments, dividends/distributions, asset sales, affiliate transactions",
availCurrent: 387, drawnCurrent: 112,
covenantCompliance: "In compliance with all financial covenants as of Dec 31, 2025",
otherFacilities: "Permian Transmission TL: $440M (2031); 5.25% Notes (2027); 4.75% Notes (2028); 8.50% Notes (2029); Second Lien",
src: "Q4 FY2025 Earnings Release (Mar 16, 2026); Earnings Call Transcript",
},
UPBD: {
facilityName: "ABL Credit Facility",
agent: "JPMorgan Chase Bank, N.A.",
syndicate: "JPM-led syndicate",
committed: 550, accordion: 0, maturity: "June 7, 2029 (springing maturity provisions)",
lcSublimit: 0, swinglineSublimit: 0,
borrowingBase: "Tied to eligible installment sales accounts, inventory, and eligible lease/rental contracts, reduced by reserves.",
bbFormula: "Lesser of (a) Aggregate Commitments and (b) BB = [Eligible Installment Sales Accounts] + [Eligible Inventory] + [Eligible Lease Contracts] - Reserves",
bbComponents: [
{ category: "Eligible Installment Sales Accounts", advanceRate: "85% of net eligible", description: "Receivables from Rent-A-Center and Acima lease-to-own installment contracts. Must be current (not >60 days delinquent), subject to debtor creditworthiness criteria, geographic concentration limits, and loss rate adjustments based on rolling 12-month charge-off experience.", source: "ABL Credit Agreement (Feb 2021, as amended)" },
{ category: "Eligible Inventory", advanceRate: "75% of NOLV", description: "Rent-to-own merchandise (appliances, electronics, furniture, computers) at store locations and distribution centers. Appraised annually. Excludes damaged/returned merchandise, items >18 months in inventory, and customer-held merchandise not on active lease.", source: "ABL Credit Agreement" },
{ category: "Eligible Lease Contracts", advanceRate: "65% of NPV", description: "Active Acima virtual lease-to-own contracts with retail partners. Valued at net present value of remaining contractual payments. Subject to merchant concentration limits, delinquency haircuts, and early buyout option adjustments.", source: "ABL Credit Agreement" },
{ category: "Reserves", advanceRate: "N/A (deducted)", description: "Charge-off reserves (based on portfolio loss experience), rent/occupancy reserves, priority payable reserves (wages, taxes), dilution reserves, stolen/damaged merchandise reserves", source: "ABL Credit Agreement" },
],
bbAvailCalc: { grossBB: "~$700M (estimated)", lessReserves: "~$150M", netAvailability: "$550M", excessAvailability: "$550M (fully undrawn)", trigger: "No springing financial covenant. Borrowing base structure serves as primary credit protection. Springing maturity: facility matures 91 days before any senior secured debt maturity exceeding $100M." },
pricing: "Adjusted Term SOFR + margin (1.50%-2.00%). Total rate: 6.28% at Sep 30, 2025 (2.00% margin). Unused fee: 0.250%-0.375%.",
pricingGrid: [
{ level: "Level I", condition: "Avg. Excess Availability >= 66.67% of Line Cap", sofrSpread: "1.50%", baseRateSpread: "0.50%", unusedFee: "0.250%" },
{ level: "Level II", condition: "Avg. Excess Availability >= 33.33% and < 66.67%", sofrSpread: "1.75%", baseRateSpread: "0.75%", unusedFee: "0.375%" },
{ level: "Level III", condition: "Avg. Excess Availability < 33.33% of Line Cap", sofrSpread: "2.00%", baseRateSpread: "1.00%", unusedFee: "0.375%" },
],
pricingNotes: "Adjusted Term SOFR includes 10 bps CSA + 26.16 bps tenor spread adjustment. Floor: 0.50%. Current level: Level III (2.00% margin) per 10-Q disclosure. Total all-in rate: 6.28% as of Sep 30, 2025. Facility currently undrawn — unused commitment fee accruing.",
security: "Substantially all assets of Upbound Group and restricted subsidiaries",
securityDetail: {
pledgedAssets: [
"All accounts receivable (installment sales, lease contracts, rental receivables)",
"All rental merchandise inventory (in-store and in-distribution)",
"All Acima virtual lease-to-own contracts and related payment streams",
"All deposit accounts and securities accounts (subject to DACAs)",
"All equipment (store fixtures, delivery vehicles, IT infrastructure)",
"All general intangibles including customer databases and software platforms",
"100% equity in all domestic subsidiaries (Rent-A-Center, Acima, Franchising)",
],
excludedAssets: [
"Real property (all stores are leased — no mortgage collateral)",
"Intellectual property subject to separate IP security agreement",
"Assets of franchisee locations (independent operators)",
"De minimis assets below threshold",
],
intercreditorNotes: "ABL has first priority on all current assets (receivables, inventory, lease contracts, deposits). Senior Secured Term Loan (~$800M) shares pari passu first-priority lien on fixed assets and IP, with ABL having super-priority on ABL Priority Collateral via intercreditor agreement. Senior Unsecured Notes are structurally subordinated.",
controlAgreements: "DACAs on all material bank accounts. Cash dominion triggered when excess availability falls below $55M (10% of commitments) for 5 consecutive business days.",
},
financialCovenants: [
{ covenant: "Borrowing Base Limit", test: "Borrowings <= lesser of BB and commitments", status: "Active", notes: "No standalone financial maintenance covenant -- relies on BB structure" },
],
negativeCov: "Restrictions on: liens, sale-leasebacks, additional indebtedness, guarantees, mergers/consolidations, asset sales, dividends, restricted payments, and subordinated debt redemption",
availCurrent: 550, drawnCurrent: 0,
covenantCompliance: "In compliance as of Sep 30, 2025",
otherFacilities: "Senior Secured Term Loan (~$800M); Senior Secured Notes; Senior Unsecured Notes",
src: "10-Q Q3 FY2025; 10-Q Q1 FY2025; Original ABL (Feb 2021)",
},
WSC: {
facilityName: "Amended ABL Revolver (Seventh Amendment)",
agent: "Bank of America, N.A.",
syndicate: "BofA Securities, JPMorgan, PNC, Wells Fargo, M&T Bank, MUFG, ING Capital ($4.0B total commitments pre-accordion)",
committed: 3000, accordion: 1000, maturity: "October 16, 2030",
lcSublimit: 0, swinglineSublimit: 0,
borrowingBase: "Fleet NOLV (Net Orderly Liquidation Value) + eligible lease receivables + other eligible assets. BB significantly exceeds committed facility.",
bbFormula: "Lesser of (a) $3.0B Cap and (b) BB (Fleet NOLV + Eligible Receivables + Other) - Outstanding Borrowings - LCs",
bbComponents: [
{ category: "Fleet NOLV", advanceRate: "85% of appraised NOLV", description: "Modular buildings (offices, classrooms, healthcare), portable storage containers, and specialty units. Appraised quarterly by independent firm (Hilco/GA). Fleet of ~350,000 units. NOLV reflects orderly liquidation value net of removal/transport costs. This is the dominant component (~80% of BB).", source: "ABL Seventh Amendment (Oct 2025); 10-Q Q3 FY2025" },
{ category: "Eligible Lease Receivables", advanceRate: "85%", description: "Monthly lease receivables from modular/storage rental contracts. Typically 12-36 month lease terms with high renewal rates (~80%). Subject to: 60-day aging cutoff, debtor concentration (no single customer >5%), government contract receivables at reduced advance rate, and cross-aging exclusions.", source: "ABL Seventh Amendment" },
{ category: "Eligible Value-Added Products", advanceRate: "70%", description: "VAPS (value-added products and services) receivables: furniture, fixtures, steps/ramps, HVAC, and delivery/installation charges billed on active leases", source: "ABL Seventh Amendment" },
{ category: "Reserves", advanceRate: "N/A (deducted)", description: "Fleet maintenance/refurbishment reserves, environmental reserves (hazmat/asbestos remediation for older units), rent reserves for branch yards, insurance reserves, priority payable reserves, availability block", source: "ABL Seventh Amendment" },
],
bbAvailCalc: { grossBB: "~$4,500M (estimated — fleet value substantially exceeds cap)", lessReserves: "~$1,500M (reserves + $3B commitment cap)", netAvailability: "$3,000M (capped by commitment)", excessAvailability: "$1,400M ($3,000M cap - $1,484M drawn - $116M LCs)", trigger: "Springing FCCR triggered if excess availability < greater of $225M and 7.5% of Line Cap" },
pricing: "Term SOFR + 137.5 bps (down from 160 bps); Base Rate + 37.5 bps. Step-downs to 125 bps / 112.5 bps. ~$5M/yr savings.",
pricingGrid: [
{ level: "Level I", condition: "Avg. Excess Availability >= 66.67% of Line Cap", sofrSpread: "1.125%", baseRateSpread: "0.125%", unusedFee: "0.200%" },
{ level: "Level II", condition: "Avg. Excess Availability >= 33.33% and < 66.67%", sofrSpread: "1.250%", baseRateSpread: "0.250%", unusedFee: "0.250%" },
{ level: "Level III", condition: "Avg. Excess Availability < 33.33% of Line Cap", sofrSpread: "1.375%", baseRateSpread: "0.375%", unusedFee: "0.375%" },
],
pricingNotes: "Seventh Amendment (Oct 2025) repriced facility ~22.5 bps tighter, saving ~$5M/yr. Term SOFR includes 10 bps CSA. Floor: 0%. Current level: Level III (1.375% margin) given ~49% utilization. Facility is the company's primary financing vehicle — heavily utilized for fleet acquisitions and M&A. UK borrower tranche removed in Seventh Amendment.",
security: "Senior secured first-priority lien on substantially all assets (US Facility; UK provisions removed in Seventh Amendment)",
securityDetail: {
pledgedAssets: [
"Entire modular/storage fleet (~350,000 units across US and Canada)",
"All accounts receivable (lease receivables, delivery/installation, VAPS)",
"All deposit accounts and securities accounts (subject to DACAs)",
"All equipment (delivery trucks, cranes, branch yard equipment)",
"All general intangibles including customer contracts and software platforms",
"100% equity in all domestic subsidiaries; 65% of first-tier foreign subs",
"All intellectual property (WillScot, MODSPACE, Mobile Mini brands)",
"All real property interests in owned branch yards (mortgages filed)",
],
excludedAssets: [
"UK subsidiary assets (removed from collateral pool in Seventh Amendment)",
"Assets of unrestricted foreign subsidiaries beyond equity pledges",
"Certain immaterial leasehold interests below $2M threshold",
],
intercreditorNotes: "ABL has first priority on all assets (fleet, receivables, deposits, equipment). Secured Notes (4.625% 2028, Secured 2029, Secured 2031 totaling ~$1.56B) share pari passu lien on fixed assets/IP but are subordinated to ABL on ABL Priority Collateral via intercreditor agreement. ABL has payment priority in enforcement scenarios. No unsecured debt outstanding.",
controlAgreements: "DACAs on all material bank accounts. Cash dominion triggered when excess availability falls below $225M for 5 consecutive business days. Revenue concentration account at BofA with daily sweep mechanics during Cash Dominion periods.",
},
financialCovenants: [
{ covenant: "Springing FCCR", test: "Triggered when excess availability below threshold", status: "Not triggered", notes: "No ongoing financial maintenance covenant when availability above trigger" },
],
negativeCov: "Customary: restrictions on additional indebtedness, liens, investments, restricted payments, asset sales, mergers, affiliate transactions",
availCurrent: 1400, drawnCurrent: 1484,
covenantCompliance: "In compliance as of Sep 30, 2025",
otherFacilities: "4.625% Secured Notes (2028, ~$496M); Secured Notes (2029, ~$525M); Secured Notes (2031, ~$535M)",
src: "8-K (Oct 17, 2025 -- Seventh Amendment); 10-Q Q3 FY2025",
},
BEUSA: {
facilityName: "Private — not publicly available",
agent: "N/A", syndicate: "Private bank group", committed: 0, accordion: 0, maturity: "N/A",
lcSublimit: 0, swinglineSublimit: 0,
borrowingBase: "Not disclosed (private). Assumed standard OFS ABL on eligible receivables and equipment.",
bbFormula: "Not available", pricing: "Not disclosed", security: "Assumed secured by company assets",
financialCovenants: [{ covenant: "Not disclosed", test: "N/A", status: "N/A", notes: "Rely on bank group reporting" }],
negativeCov: "Not disclosed", availCurrent: 0, drawnCurrent: 0,
covenantCompliance: "Not available — monitor via bank group", otherFacilities: "N/A",
src: "Private company — no SEC filings",
},
JSWUSA: {
facilityName: "Private — not publicly available",
agent: "N/A", syndicate: "Private bank group", committed: 0, accordion: 0, maturity: "N/A",
lcSublimit: 0, swinglineSublimit: 0,
borrowingBase: "Not disclosed. Assumed standard steel/metals ABL on eligible receivables, inventory, equipment.",
bbFormula: "Not available", pricing: "Not disclosed", security: "Assumed secured; implicit parent support from JSW Group",
financialCovenants: [{ covenant: "Not disclosed", test: "N/A", status: "N/A", notes: "Rely on bank group + JSW Group disclosures" }],
negativeCov: "Not disclosed", availCurrent: 0, drawnCurrent: 0,
covenantCompliance: "Not available — monitor via bank group", otherFacilities: "Parent: JSW Group implicit support",
src: "Private company — no SEC filings",
},
};

